civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/src/Blocks/AbsenceLinks.php

Here are the required backend changes for PCHR-251
* Added the `civihr_form--modal` class (see [here](https://github.com/compucorp/civihr-employee-portal-theme/pull/7)
* Amended the structure of the form to implement the new custom modal (see [here](https://github.com/compucorp/civihr-employee-portal-theme/pull/7)
* Removed the documents field, as it was not present in the design
* **To improve:** added a function that shows/disable the selected dates section
* Call the new custom modal when clicking on the buttons

PCHR-251: Holiday request form (backend)

---

civihr_employee_portal/civihr_employee_portal.module

PCHR-341: Fix issues with period calculations on request leave form

---

civihr_employee_portal/views/templates/views-view-field--civihr-staff-directory--page--image-URL.tpl.php
civihr_employee_portal/views/views_export/views_hr_staff_directory.inc

Put the user picture in its own template, so that if the user didn't upload any image we can use the default one

PCHR-420: Default user picture also on Staff Directory

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
civihr_employee_portal/js/filters.js
civihr_employee_portal/views/templates/views-view--approvals--block-1.tpl.php
civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
civihr_employee_portal/views/templates/views-view-table--approvals--block.tpl.php
civihr_employee_portal/views/views_export/views_documents.inc
civihr_employee_portal/views/views_export/views_manager_approval_list.inc

(For frontend-related things that are mentioned here, please refer to https://github.com/compucorp/civihr-employee-portal-theme/pull/15 )
Things done:
* Cleaned up markup code of the "Documents" and "Manager approvals" templates
* Implemented the `chr_table-w-filters` component
* Refactored javascript files ([here](https://github.com/compucorp/civihr-employee-portal-theme/pull/15) are more details)
* Amended the default classes applied to blocks/views

 PCHR-412: Responsive dashboard (2/2)

---

civihr_employee_portal/src/Forms/AbsenceRequestForm.php

Minor fix re a label in the form

PCHR-251: Fix Absence form label

---

civihr_employee_portal/views/views_export/views_calendar_absence_list.inc

Updating the colors for the individual absence types on the calendar, so that they match the designs

PCHR-413: Update calendar colors

---

civihr_employee_portal/src/Blocks/ManagerCalendar.php

Things done:
* Simplified the structure of the `<td>`s containing an entry in the calendar
* Added classes related to the `.chr_calendar--manager` component

PCHR-419: Manager calendar

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/src/Blocks/AbsenceLinks.php
civihr_employee_portal/src/Blocks/SicknessLinks.php
civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php
civihr_employee_portal/views/templates/views-view-field--civihr-staff-directory--page--display-name.tpl.php
civihr_employee_portal/views/views_export/views_hr_staff_directory.inc

Things done
* Amending the filters form: added bootstrap grid elements and removed labels and replaced them with placeholder attributes
* Merged the user picture and user name in one field via custom template
* Implemented `.chr_actions-wrapper` and `.chr_profile-pic` (see [this PR](https://github.com/compucorp/civihr-employee-portal-theme/pull/24))

PCHR-418: Staff Directory

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/src/Blocks/AbsenceLinks.php
civihr_employee_portal/views/templates/views-view-field--hr-documents--hr-resources--nothing.tpl.php
civihr_employee_portal/views/templates/views-view-field--hr-documents--hr-resources-modal--nothing.tpl.php
civihr_employee_portal/views/templates/views-view-fields--hr-documents--hr-resources-modal.tpl.php
civihr_employee_portal/views/templates/views-view-unformatted--hr-documents--hr-resources.tpl.php
civihr_employee_portal/views/views_export/views_hr_documents.inc

Things done
* Move javascript with custom modal settings so it's globally available
* Implement `.chr_hr-resource` component
* Implement `.chr_action--icon--download` action
* Amend HR Documents view default settings

PCHR-416: HR Resources

---

civihr_employee_portal/views/templates/views-view-field--hr-documents--hr-resources-modal--nothing.tpl.php

Amended the structure of the hr resource modal

PCHR-414: Responsive modals

---

civihr_employee_portal/views/templates/views-view-field--civihr-staff-directory--page--last-name.tpl.php
civihr_employee_portal/views/views_export/views_hr_staff_directory.inc

We use the "Last Name" column as the container of the user pic + display name fields, so that the column will be sortable by last name only

PCHR-454: Add Last Name sortable column with pic + display name

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/views/templates/views-view-table--approvals--page.tpl.php
civihr_employee_portal/views/views_export/views_manager_approval_list.inc

*(For frontend-related things that are mentioned here, please refer to https://github.com/compucorp/civihr-employee-portal-theme/pull/29)*
Things done:
* Added a specific template for the "All absences" view, so that the custom modal markup could be implemented
* Refactored how we set up the CTools modals, so that it will be easier to add new types in the future

PHCR-414: All Absences (1/2)

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/js/scripts.js
civihr_employee_portal/views/views_export/views_manager_approval_list.inc

Things done:
* Used custom large modal for Pick Days
* Amended the pick days form
* Refactored the code
* Implemented the chr_action component on buttons
* Implemented the modal-civihr-custom component markup
* Show the staff notes only if present
* Added a class to the table so that it can be targeted by CSS
* Amended the pick days script
* Show/Hide the manager notes' parent element, as it's now wrapped in it and the parent must be hidden as well if the notes are hidden
* Removed console logs

PHCR-414: Pick Days (2/2)

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/views/templates/views-view--Tasks--block.tpl.php
civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php

Amended the markup of the "Create Task" modal, using the new attribute `#label_class` added in https://github.com/compucorp/civihr-employee-portal-theme/pull/34

 PCHR-414: Create Task modal

---

civihr_employee_portal/src/Forms/AbsenceRequestForm.php
civihr_employee_portal/views/templates/views-view--Tasks--block.tpl.php
civihr_employee_portal/views/templates/views-view--approvals--block-1.tpl.php
civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php

Implemented the `chr_custom-select` element, introduced [here](https://github.com/compucorp/civihr-employee-portal-theme/pull/35)

PCHR-508: Custom select

---

civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php
civihr_employee_portal/views/templates/views-view-field--civihr-staff-directory--page--last-name.tpl.php

Implemented the `chr_profile-card` component introduced in https://github.com/compucorp/civihr-employee-portal-theme/pull/45

PCHR-502: Fix text wrap in Staff Directory table

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/views/views_export/views_abence_entitlement.inc
civihr_employee_portal/views/views_export/views_absence_list.inc
civihr_employee_portal/views/views_export/views_manager_approval_list.inc
civihr_employee_portal/views/views_export/views_my_details_block.inc

First letter of each word in title should be uppercase.

PCHR-243 - Uppercase in Block Titles

---

civihr_employee_portal/src/Blocks/ManagerCalendar.php

…calendar when leaves requested for same duration

sorts issue in manager calendar - PCHR-277

---

civihr_employee_portal/templates/civihr-employee-portal-custom-reports.tpl.php

PCHR-628: Change size of calendar form field

---

civihr_employee_portal/templates/civihr-employee-portal-custom-reports.tpl.php

PCHR-757: Switch type of arrow for charts navigation

---

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc

Added ID's to "tasks" and "documents", so they can be linked to from outside.
This PR is required by:  https://github.com/compucorp/civihr-tasks-assignments/pull/9

PCHR-434: Added ID's to panels, so they can be linked to

---

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc

Removed Prefixes (Mr. Mrs, Dr. etc.) from staff directory search autocomplete

PCHR-752: Remove prefix from Staff Directory Search

---

civihr_employee_portal/js/reports.js
civihr_employee_portal/templates/civihr-employee-portal-custom-reports.tpl.php

Added "summary" table under reports:

PCHR-788: Added summary table in reports

---

civihr_employee_portal/src/Forms/AbsenceRequestForm.php

This PR allows the user to re-request the cancelled leaves again.

PCHR-748: Enable re-requesting of cancelled leaves

---

civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php

Patch adds a `due date` column in Tasks block on SSP

PCHR-746: Add Due Date column in Tasks Block

---

civihr_employee_portal/src/Blocks/ManagerCalendar.php
civihr_employee_portal/views/views_export/views_calendar_absence_list.inc

Removed cancelled leaves from "Manager Absence Approval" block and "My Leave" block on SSP

PCHR-817: cancelled leaves on calendar

---

civihr_employee_portal/src/Blocks/ManagerCalendar.php

Fetch absences belonging to current year only for Manager Calendar Block

PCHR-818: Fetch absences only for current year

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/src/Blocks/ManagerCalendar.php

Changes will show absence requests till the end of last day of relationship

PCHR-831: Show leave request until the end day of relationships

---

civihr_employee_portal/src/Blocks/AbsenceLinks.php

PCHR-571: Move the toil button to the left

---

civihr_employee_portal/css/custom.css
civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php
civihr_employee_portal/views/templates/views-view--default.tpl.php
civihr_employee_portal/views/templates/views-view-table--civihr-report-people--civihr-report-table-people.tpl.php

Created a template file for the table's view and shows a header with the total results. It was made some changes on the nav tabs to adjust to civihr's design and added some classes on the pagination element.
The styles are in the [PR-59](https://github.com/compucorp/civihr-employee-portal-theme/pull/59)

PCHR-1007 - Individual Report Data section

---

civihr_employee_portal/civihr_employee_portal.module

In civihr_employee_portal_init() function we catch any Exception and display its message as Drupal error message.

PCHR-1071 - catching civihr_employee_portal_init() function exception and displaying as Drupal error message.

---

civihr_employee_portal/js/reports.js

I've created "Count Unique Values (not empty)" Pivot Table Aggregator which works similarly to "Count Unique Values" but doesn't count empty values such as NULL, 0 or empty string. This allows to count unique Role IDs excluding empty Role IDs which appear on Pivot Table where Job Contract doesn't have any Role created.

Creating custom Aggregator (Count Unique Values (not empty)) for Pivot Table.

---

civihr_employee_portal/civihr_employee_portal.module

- Using hook_form_alter for implementing ajax callbacks on State/Province fields.
- Using hook_node_view for implementing default values of State/Province fields.
- Creating a function returning a list of State/Province key-value pairs by given Country ID.
- Creating callback functions for handling ajax refresh of State/Province fields after changing Country field values.

PCHR-1167 - Implementing ajax callbacks handling for State/Province Emergency Contact webform.

---

civicrm_resources/civicrm_resources.module

The condition to select js/css when wildcard parameters (*.css / *.js )was being passed was not correct. The css files were being added as js scripts too. 
Added an additional condition to check filenames with regex.

PCHR-920 Custom module to load civicrm resource drupal

---

civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module

Excluding deleted Job Contracts when joining with Revision and Role data during SQL views creation.

PCHR-1092 - Excluding deleted contracts from SQL views.

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/js/reports.js
civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php

This PR fix some design issues on filters section.
It was updated the arrow icon now it's using the icon to right when the filters are closed.
***Before***
***After***
It was updated the filters date format, before the format was `yyyy-MM-dd` now is `dd/MM/yyyy`, and it was necessary to change the format before send the request to the server, to change the format it was used the library momentjs.
***Before***
***After***
It was updated the method `getModuleUrl` to fix a environment issue.
***Before***
/sites/all/modules/civicrm/tools/extensions/civihr/org.civicrm.bootstrapcivicrm/css/bootstrap-civicrm-style.css
***After***
sites/all/modules/civicrm/tools/extensions/civihr/org.civicrm.bootstrapcivicrm/css/bootstrap-civicrm-style.css

PCHR-1005: Fix filters section

---

civihr_employee_portal/templates/civihr-employee-portal-civihr-report-landing-page.tpl.php

This PR adjust some design issues. Related with https://github.com/compucorp/civihr-employee-portal-theme/pull/78
It was updated the panels header/content font size.
***Before***
***After***

PCHR-1004: Fix reports list page

---

civihr_employee_portal/civihr_employee_portal.module

After Radix theme update, 404 errors were seen in the console.
Removed the unused files

PCHR-1316: Remove unwanted lines

---

civihr_employee_portal/civihr_employee_portal.module

PCHR-1403: Remove reference to civihr_admin_theme

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php

https://github.com/compucorp/civihr-employee-portal/pull/173

PCHR-1452 - Dashboard does not load

---

civihr_employee_portal/src/Blocks/ManagerCalendar.php

https://github.com/compucorp/civihr-employee-portal/pull/174

PCHR-1318 - Fix calendar absence list notice messages

---

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
civihr_employee_portal/views/civihr_employee_portal.views.inc

Fixing notice messages in removeAdditionalCommas() and removeInactiveDepartments() module functions by adding validation for non empty Views values.

PCHR-1455 - Big notice message on staff directory

---

civihr_employee_portal/views/civihr_employee_portal.views.inc

Adding validation for Drupal View field's values into removeAdditionalCommas() and removeInactiveDepartments() SSP module functions.

PCHR-1455 - Fixing notice messages in removeAdditionalCommas() and removeInactiveDepartments() module functions.

---

civicrm_resources/civicrm_resources.module

https://github.com/compucorp/civihr-employee-portal/pull/156

PCHR-920: Changed the path for loading the files.

---

civihr_employee_portal/civihr_employee_portal.module

Resubmitting https://github.com/compucorp/civihr-employee-portal/pull/189 and addressing the Syntax errors on the SSP by allowing JSON files used by views to be accessed anonymously.

PCHR-1480: Redirect non-authorized users to /welcome-page

---

civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module

Fixing some Option Values for getting proper labels as field values in SQL views.

PCHR-1530 - Data site reports

---

civihr_employee_portal/civihr_employee_portal.install
civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.info
civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
civihr_employee_portal/civihr_leave_absences/templates/my_leave.html

Problem :
Added My Leave block that can fetch custom markup from pre-defined template file and also an angular js app defined for My Leave block that will be use to place block in whatever page/view is necessary.
Solution:
Crated new module called CiviHR Leave Absences that contains custom block to hold markup for block from pre-defined template file and angular js app i.e template file can be changed as necessary by front-end developer without having any knowledge of block processing. As this is custom block we can easily export and place in whatever region we require.

PCHR-1248: Added My Leave block fetching markup from pre-define template.

---

civihr_employee_portal/views/civihr_employee_portal.views.inc

**Requirement**
Remove view switcher in staff directory of SSP.
**Before**
**After**

PCHR-1661: Remove view switcher

---

civihr_employee_portal/features/leave_and_absences_feature/leave_and_absences_feature.module
civihr_employee_portal/features/leave_and_absences_features/leave_and_absences_features.features.inc
civihr_employee_portal/features/leave_and_absences_features/leave_and_absences_features.info
civihr_employee_portal/features/leave_and_absences_features/leave_and_absences_features.module
civihr_employee_portal/features/leave_and_absences_features/leave_and_absences_features.pages_default.inc

Renamed feature name to Leave and Absences Features and changed the ordering of My Leave menu item.

PCHR-1247: Renamed module name and changed menu ordering.

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/js/reports.js

Adding today's date as default input value in exposed date filters.

PCHR-1370 - Show today's date for default date in reports

---

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module

**Task**
Add custom template for "Manager Leave" menu item that would act as placeholder to angular js files to display number of pending leave requests using template file.
**Solution**
Added function to load the angular js app and custom template to show number of pending leave requests and this function would be called from theme template.php to add markup to Manager Leave menu item using menu_link function.

PCHR-1953: Adding custom template for showing number of pending leave requests.

---

civihr_employee_portal/civihr_employee_portal.module

In CiviHR we are now using the shoreditch theme, so theme references in the ssp needs to be updated
Related PRs:
https://github.com/civicrm/org.civicrm.shoreditch/pull/4
https://github.com/civicrm/civihr/pull/1674
https://github.com/compucorp/civihr-tasks-assignments/pull/177

PCHR-2064: Refer shoreditch theme

---

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module

As part of this PR, usage of non minified files when debugging is on is implemented for Leave and Absence.

PCHR-2003: Use non minified files when debugging is on

---

package.json

See https://github.com/civicrm/civihr/pull/1930

PCHR-2303: Improve semistandard hook

---

civihr_employee_portal/civihr_employee_portal.module

[LoginToboggan](https://www.drupal.org/project/logintoboggan) adds some features related to user login, for example _allowing users to login using either their username OR their e-mail address._
The login form had a placeholder saying "Username"
The login form name placeholder says "Username or email"

PCHR-2242: Update placeholder on login form

---

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
civihr_employee_portal/js/ta-documents-app.js
civihr_employee_portal/views/templates/views-view-table--Documents--block-1.tpl.php

The simple angular app created in #305, attach it to Documents manager view in SSP to display the Modal for the civihr_manager user.
There was not a option to display a modal in Documents manager section
1. Add `access Tasks and Assignments Files` and `access uploaded files` permissions for `civihr_manager` user. For more details about the permissions refer to technical description of #305 .
2. Added following markup for angular injection. The empty div `<div` is required to  in which the modal is placed when opened.
```html
<div data-ta-documents-manager ng-controller="ModalController as document">
<div> 
...
</div>
</div>
```
3. Add following code replacing the existing markup, which on clicked displays the modal
```html
<button
ng-click="document.modalDocument(<?php print …
```

PCHR-2146: Updates for document management widget civihr_manager

---

civihr_employee_portal/js/ta-documents-app.js
civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php

This PR makes some code refactoring and displays the spinner in Document modal removing the spinner in place of "upload" button in a document list, when trying to open a document modal.
- The spinner was displayed in place of "upload" button, when clicking the button in document list.
- The spinner was displayed in modal popup, when clicking the "upload" button in document list.
1. Display the spinner after the modal is loaded in file `civihr_employee_portal/js/ta-documents-app.js`
```js
function openModalDocument(data, role, mode) {
var modalInstance = $modal.open({
...
});
modalInstance.opened.then(function () {
$rootScope.isLoading = true;
});
}
```
2. Hide the spinner when the contacts are loaded and cached.
```js
...
vm.cacheContacts(data).then(function () {
$rootScope.isLoading = …
```

PCHR-2457: Document open buttons take very long to load on ssp

---

civihr_employee_portal/features/onboarding_slideshow/onboarding_slideshow.views_default.inc

As part of this PR, the Drupal View for the Carousel Page has been updated with pager.
Bottom pager added to the Onboarding Slideshow View.

PCHR-2708: Carousel Page View Update

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/src/Helpers/WebformHelper.php

Webform submissions are checked on login. If a user has not completed the onboarding webform they will be redirected to it. There is a bug in submission checking that means webform submissions are not correctly filtered, so if a user has other webform submissions (e.g. edit my details) it will incorrectly assume they have completed onboarding.
If a user has "edit my details" submissions, but no onboarding webform submissions they won't be redirected to the onboarding form on login.
The user will be redirected to the onboarding form if they haven't completed it, regardless of other webform submissions.
---

PCHR-2817: Fix bug in fetching webform submissions.

---

civihr_employee_portal/civihr_employee_portal.module

Contains the following PRs:
* #370

PCHR-2600: User sub-menu in admin main menu

---

civihr_employee_portal/features/onboarding_slideshow/onboarding_slideshow.views_default.inc

As part of this PR, `scrollHorz` class has been added to the Carousel page Slide Show .

PCHR-2760: Swipe Carousel

---

civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php

As part of this PR, the order of Reports is changed in SSP.
1. Added `crm_custom-select` class to the Pivot table `select`.
---

PCHR-2715: Swap Reports Order

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/src/Forms/OnboardingWebForm.php
civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
civihr_employee_portal/src/Helpers/WebformHelper.php

Fixes some issues that appeared in QA
- Work email was not being set as primary if home email was already primary
- Cancel button was navigating to either T&A dashboard or dashboard
- Save button was in the wrong place and have wrong text ("Save Configuration")
- Work email is always set as primary on submission if it is set
- Cancel button navigates to `/dashboard`
- Save button was is on the right side and has the right text ("Save")
---

PCHR-2339: QA Fixes

---

civihr_employee_portal/js/reports.js
civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php

As part of this PR, bugs related to SSP Reports tabs, has been fixed. 
The tabs in the reports, did not support routing, so when the pagination was clicked in Data tab, the page got refreshed and the tabs index were reset.
1. Added routing to the tabs. 
- Tab hash has been added to the `anchor` tags.
- Added `switchTabsOnLoad()` function, which switches the tabs using url hash, during page load.
Semistandard Fixes has been done.
---

PCHR-2715: Swap Reports

---

civihr_employee_portal/views/views_export/views_emergency_contacts.inc

As part of this PR, the Delete button is added to the Emergency Contacts and Dependents View.
It also adds a filter to the view to only show emergency contacts related to the current logged in contact.
For more details refer https://github.com/compucorp/civihr-employee-portal-theme/pull/273
---

PCHR-2850: Add Delete button

---

civihr_employee_portal/js/ta-documents-app.js

Simply fixes names of modules and services, due to the changes done in [this PR](https://github.com/compucorp/civihr-tasks-assignments/pull/291)

PCHR-3032: Fix dependencies names

---

civihr_employee_portal/civihr_employee_portal.install
civihr_employee_portal/civihr_employee_portal.module

This PR includes the commit of https://github.com/compucorp/civihr-employee-portal/pull/430, which is a sub-task of PCHR-3003. 
The commit hash here is different from the one on the original PR. The reason is that the PR was merged to the `PCHR-3003-default-reports-configuration` branch, which was created based on the `PCHR-2592-reporting-ux-improvements` branch and that already had some commits from another ticket that is not done yet. Since now we need to merge this to staging, we cannot have the commits from the ticket that is not done yet, so I created a new `PCHR-3003-default-reports-configuration-2` branch from staging and cherry-picked only the commit we need.

PCHR-3003: Create default reports configuration

---

.gitignore
package-lock.json
package.json

See https://github.com/civicrm/civihr/pull/2464

PCHR-3259: Use lint staged for pre-commit linters

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
civihr_employee_portal/js/tasks.js
civihr_employee_portal/templates/tasks_notification_badge.html

This PR contains the code from following already approved PRs
https://github.com/compucorp/civihr-employee-portal/pull/469
This ticket though part of an epic, can be delivered as separate features, so there is no epic branch.

PCHR-3673: Count of Assigned Task and Documents

---

civihr_employee_portal/civihr_employee_portal.module
civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
civihr_employee_portal/views/templates/views-view--manage-hr-resources-page.tpl.php

As part of this PR, a New Page for Managing HR Resources has been added and styled.
**Desktop**
**Mobile**

PCHR-3703: New page for Managing HR Resources

---

civihr_employee_portal/views/templates/views-view--my-details.tpl.php

Title for Contact Details not being displayed.

PCHR-3970: Title for Contact Details not Displayed

---

civihr_employee_portal/src/View/StaffDirectoryView.php

This PR merges implementation of `Fix SSP Filters to take into account role start/end dates` to staging.
Included tickets are:
Ticket No. | PRs 
------ | ---- 
PCHR-4073 | [#533](https://github.com/compucorp/civihr-employee-portal/pull/533)

PCHR-3963: Fix SSP Filters to Take into Account Role Start End Dates

---

package-lock.json

See https://github.com/compucorp/civihr/pull/2828 for overview
0 vulnerabilities left
No manual changes done

PCHR-4046: Fix security vulnerabilities

---

civihr_employee_portal/civihr_employee_portal.module

This PR removes all occurrencies of hrrecruitment on the code
There was some references to hrrecruitment left on the code
All references to hrrecruitment has been removed

PCHR-4139: Removing All Occurrencies of HRRecruitment

---

civihr_employee_portal/views/views_export/views_my_details_block.inc

We want to add the external ID to the "My Details" view
The field was not displayed
The field is displayed
---

PCHR-4031: Add external ID field to view

---

civihr_employee_portal/views/views_export/views_mydetails_personal.inc

We want to add the "External ID" to a view on the `/hr-details` page
The field was not present
The "External ID" field is displayed
---

PCHR-4031: Add External ID to View

---

civihr_employee_portal/civihr_employee_portal.install
civihr_employee_portal/src/Forms/OnboardingWebForm.php
civihr_employee_portal/src/Helpers/UrlHelper.php
civihr_employee_portal/tests/Helpers/UrlHelperTest.php
civihr_employee_portal/updates/7042.php
civihr_employee_portal/views/views_export/views_mydetails_personal.inc

Photos uploaded from the onboarding form are not displayed in either the contact summary page or the SSP. This PR fixes both those issues.
- Image URLs with `photo=0` in it would not display on the contact profile page
- Image URLs uploaded from the onboarding form would not display on the `/hr-details` personal details section
- Contact images are displayed regardless of where they're uploaded from
- Existing images with `photo=0` in them are fixed to remove this
- Upgrade functions in files in the `updates` directory are automatically included
When fetching the image URL, `\CRM_Utils_File::getImageURL` the mime type incorrectly be `image/jpg?photo=0` for a jpg image with `photo=0` in the query string. This has a knock-on effect meaning the image will be treated as a file and not …

PCHR-4281: Image Display Fixes

---

civihr_employee_portal/src/View/MyDetailsView.php

Check https://github.com/compucorp/civihr/pull/2939 for more details

PCHR-4396: Fix "creating default object from empty value" warning on the SSP
