compucorp/civihr-employee-portal

civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php
The profile pic on Safari, in the My Details block, appeared misaligned. There were some CSS rules applied to it via a class that didn't look to me any useful, so I removed the class
=> PCHR-429: Fix profile pic on Safari

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc, civihr_employee_portal/src/Blocks/AbsenceLinks.php, civihr_employee_portal/src/Blocks/SicknessLinks.php, civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php, civihr_employee_portal/views/views_export/views_absence_list.inc
*(For frontend-related things that are mentioned here, please refer to https://github.com/compucorp/civihr-employee-portal-theme/pull/14 )*
Things done:
* Amended `civihr_employee_portal_make_link`
* It accepts an additional `$class` parameter, which adds custom classes to the link
* In case of a `.chr_action`, it wraps the action's label in a `span` so that, if needed, the action can be responsive
* Added by default the `view--w-table` class to the absence list view
* Removed the labels of the exposed forms in the "My Leave" and "My Sickness Report" blocks, since they were used as a header, but now the blocks have their proper header displayed instead
* Implemented the new `.chr_action` component
* Refactored the "My Details" markup
=> PCHR-412: Responsive dashboard

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
In order for the styling of the block to work properly, the "My Details" block must have the .chr_panel--my-details class applied by default
=> PCHR-412: Add class to My Details block

calendar/theme/theme.inc
Just swapping placement of the calendar legend elements. The color square was put after the label, so it had to be absolutely positioned in order for it to be on the left of the label. It's just easier to actually change the order in the backend code
=>  PCHR-413: My Calendar modal responsiveness

civihr_employee_portal/js/filters.js
Whenever an absence was approved/reject and its row was deleted from the table, the filters list on the side was being duplicated instead of being refreshed.
This fix makes sure that the list is cleared before being rebuilt from scratch
=> PCHR-412: Fix Manager Approve Absence panel bug

civihr_employee_portal/civihr_employee_portal.module
For the reports page, although the page is being served by Drupal, we want to use the look-and-feel of the CiviHR admin. For this reason we explicitly apply the new admin theme (https://github.com/compucorp/civihr-employee-portal-theme/pull/40) on it
=> PCHR-513: Implement new CiviHR admin them on reports page

civihr_employee_portal/views/views_export/views_absence_list.inc
--no-padding section class works only with custom modals.
Bug was caused by using this class in .modal-default.
Solved by changing modal class to .modal-civihr-custom--large instead of .modal-default.
=> Use Custom Modals in 'My Leave' Block

civihr_employee_portal/js/reports.js
Applying the theme's chart colors and fixing the legend text color
=> PCHR-630: Adjust chart colors

civihr_employee_portal/js/reports.js
The tooltips were being redrawn only when the user used the handles to slide to a new value, but not when the user clicked directly on a point of the slider line. Attaching the redraw functionality on the "change" event listener solves the issue
=> PHCR-757: Redraw tooltip on slider click

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/reports.js, civihr_employee_portal/src/Forms/ReportSettingsForm.php, civihr_employee_portal/templates/civihr-employee-portal-custom-reports.tpl.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_absence_duration.inc, civihr_employee_portal/views/views_export/report_days_taken_location_absence.inc, civihr_employee_portal/views/views_export/report_fte_level.inc, civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
- More abstracted whitelisting for the template file - based on the report types it will load the templates/civihr-employee-portal-custom-reports-filter-result.tpl file. Previously the report types were hardcoded
- Added View FTE / Level - from the demo presentation
- Added new relationship handler -> absence view can now have a relationship with contact entity. Previously the absence view we were unable to link it to contact entity in the views
- Added raw result type for duration handler - this raw result type is used to calculate the duration in the absence days taken report
- Added days taken view and report
- Fixed date range slider to show month names and not days
- Added some more default X axis filter types so they can be set in the settings page and enabled
=> Pchr 262 - absence reports, refactor, settings + fixes

civihr_employee_portal/views/views_export/views_appraisals.inc
Restricting the 'Appraisal' SSP top menu item only to Admin and Manager roles + changing the menu item title from 'Appraisal Manager' to 'Appraisal'.
=> PCHR-792 - Restricting the 'Appraisal' SSP top menu item to 'admin' and 'manager' roles only.

civihr_employee_portal/civihr_employee_portal.module
Issue:
The cancellation emails were getting sent to old managers as well.
Solution:
Modify function `function _getManagerContacts($contact_id)` to return only active managers.
=> UY-24: Donot send cancellation email to Old Manager

civihr_employee_portal/views/civihr_employee_portal.views.inc
Expose `id` field from civicrm table `civicrm_value_emergency_contacts_21` to drupal views.
=> UY-22: Expose Emergency Contact ID field in drupal Views

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/src/Blocks/ManagerCalendar.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_manager_id.inc, civihr_employee_portal/views/views_export/views_manager_approval_list.inc
PR addresses the following issue:
When the manager of a contact is changed, the new manager is not able to view the absences that were assigned to the past manager and hence not able to accept/reject those absences either.
=> PCHR-759: Show leave request for past managers

civihr_employee_portal/civihr_employee_portal.module
Modified `function relationActiveAndCurrent` to return `true` if start date for relationship is in the past or is empty.
=> PCHR-830: Donot show leave requests for future manager

civihr_employee_portal/views/includes/civihr_employee_portal_filter_absence_period.inc
My leave block absence period selector was not pointing to the current period.
I fixed it to set the default option to the current period based on the current date , and in case the current date do not fit into any absence period it will default to the latest period in term of End Date.
=> PCHR-798: Improve my leave block default absence period to the current one

civihr_employee_portal/src/Blocks/ManagerCalendar.php, civihr_employee_portal/views/views_export/views_calendar_absence_list.inc
Both calendars shouldn't display rejected leaves. I've changed the view used to generate the My Leave calendar and the the query used to generate the Manager Absence Approval calendar to filter out those leaves.
Bellow are some screenshots showing the results:
Given 3 leave requests (one rejected, one cancelled and one waiting approval)
Before the change, both calendars displayed the rejected requests:
After the change, the rejected requests are no longer displayed on both calendars:
=> PCHR-851: Removes rejected leaves from My Leave and Manager Absence Approval calendars

civihr_employee_portal/civihr_employee_portal.module
The following permissions were added:
- Access CiviHR Leave and Absences
- Manage CiviHR Leave and Absences
Here you can see the permissions available on Drupal:
=> PCHR-938: Add Leave & Absences CiviHR permissions

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.user_permission.inc, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info
"**administer roles and teams**" are added to be enabled by default for "**civihr_admin**" and "**administer**" Drupal roles.
=> PCHR-997: new permission - manage roles and Teams

civihr_employee_portal/civihr_employee_portal.module
If someone created a new role and added a user to that role , then that user will not be able to see "My details" menu item since the roles allowed to view that menu item is hard-coded to limited set of roles which are :
**('civihr_staff', 'civihr_manager', 'civihr_admin', 'administrator' ) .**
The code changed to fetch all existing roles except the default drupal roles **( 'anonymous user', 'authenticated user' )** and updating "access arguments" for my details menu item to use any of these fetched roles.
**-- Before**
**-- After**
=> PCHR-998: View My details menu item to users with newly created roles

.editorconfig
Adding a [.editorconfig](http://editorconfig.org/) file to standardize coding style for all the project's developers/contributors
=> PCHR-1022: Adding .editorconfig file to repo

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/reports.js, civihr_employee_portal/templates/civihr-employee-portal-civihr-report-landing-page.tpl.php
It was styled the reports list page to be like the PSD and added a collapse effect on 'Reports Settings' block.
**Before**
**After**
It was overridden the markup, and created a method `setTitleMarkup` to set the title markup.
It was fixed the variable `$base_url` position, it was been using before be defined. And was added the `report.js` and `reqangular.min.js` into /reports
Created a controller for the settings block, with `isCollapsed` property.
=> PCHR-1004: Reports list page

civihr_employee_portal/templates/civihr-employee-portal-civihr-report-settings-age-group.tpl.php
It was styled the _reports settings - age group_ page using the default styles `.panel` and `table`, also was added a panel header to show the results total.
**Before**
**After**
=> PCHR-1122: Reports settings - Age group

civihr_employee_portal/views/includes/views_between_dates_filter_handler.inc
Modifying views_between_dates_filter_handler.inc custom Drupal View Handler allowing to specify a date value between two date fields (columns) and adjusting it to allow NULL dates (optionally) and custom format of input date.
=> PCHR-1106 - Customize 'value between dates' View Handler to handle NULL values and custom input date format.

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.user_permission.inc, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc, civihr_employee_portal/views/views_export/views_abence_entitlement.inc, civihr_employee_portal/views/views_export/views_absence_list.inc, civihr_employee_portal/views/views_export/views_appraisals.inc, civihr_employee_portal/views/views_export/views_hr_documents.inc, civihr_employee_portal/views/views_export/views_hr_staff_directory.inc, civihr_employee_portal/views/views_export/views_hr_vacancies.inc, civihr_employee_portal/views/views_export/views_my_details_block.inc, civihr_employee_portal/views/views_export/views_tasks.inc
Currently most of the views and pages are tied to roles in SSP ( https://compucorp.atlassian.net/wiki/display/PCHR/Configuring+a+newly+created+user+role ) .... But we need  things to be more simpler instead of configuring every view and page each time a new role created ..  so I defined a set on new permissions which are :
'view my details' => array(
'title' => t('View My Details'),
'description' => t('Availability for the user to view my details block and page')
),
'view my tasks block' => array(
'title' => t('View My Tasks Block'),
'description' => t('Availability for the user to view my tasks block')
),
'view appraisals' => array(
'title' => t('View Appraisals'),
'description' => t('Availability for the user to view appraisals block and page')
),
'view my leave block' => array(
'title' …
=> PCHR-1077: Use permissions instead of roles for blocks and pages

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/src/Forms/AbsenceRequestForm.php, civihr_employee_portal/views/includes/civihr_employee_portal_handler_area_totals.inc, civihr_employee_portal/views/views_export/views_abence_entitlement.inc, civihr_employee_portal/views/views_export/views_absence_list.inc
The "Sick" absence type is a special case of an absence, as it is displayed separately from the other types and it has a dedicated modal to request it.
The problem is that in order to distinguish it from the other types, we rely on its name, which is always assumed to be "Sick"
```php
if ($absence_type['title'] == 'Sick') {
// ...
}
```
That means that the moment someone changes the name even slightly, say from "Sick" to "Sick Leave", the system breaks
The solution is still temporary, and only because we have a new Leave&Absences system coming in the near future. Basically instead of checking for the exact "Sick" name, we just check if "Sick" is present
```php
return preg_match('/^sick/i', $absenceName);
```
Also some views had to have the filters updated to make them less strict about …
=> PCHR-1136: Handle sickness absence with different name

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/views/includes/civihr_employee_portal_handler_task_contacts.inc
Fixing Dashboard error appearing when some of the Tasks have no Contact ID:
Notice: Undefined index: id in civihr_employee_portal_handler_task_contacts->render() (line 25 of /var/www/civicrm-buildkit/build/hr15-develop/sites/all/modules/civihr-custom/civihr_employee_portal/views/includes/civihr_employee_portal_handler_task_contacts.inc).
- Task Contacts view handler was trying to get Contact data basing on provided contact_id which was empty in some cases. Currently the handler doesn't try to fetch Contact data if contact_id is empty.
Also I've added an activity contact fields (source contact, assignee contact and target contact) as mandatory fields in Task and Document entities so the values should be specified when creating Tasks / Documents (Pull Request: …
=> PCHR-1160 - Fixing anonymous user notice messages and Tasks contacts view handler empty ID warnings.

civihr_employee_portal/civihr_employee_portal.module
The views data field has  an embedded view which is supposed to inherit the contextual filters. Looks like something wrong with auto submit. The auto submit is not called on first page load. Fixed that by forcing form to submit on page load.
=> PCHR-1158: Add js to trigger auto-submit on views data on My leave block.

civihr_employee_portal/civihr_employee_portal.drush.inc
When using `drush refresh-node-export-files`, the `nid`s of the newly generated webforms weren't then set as variable automatically, this PR fixes that
=> PCHR-959: Set drupal variables when creating webforms

civihr_employee_portal/views/views_export/views_abence_entitlement.inc
My leave block was viewing the name of leave types ( which may contain underscores ) instead of their titles 
**Before :**
and now it's fixed 
**Now :**
=> PCHR-860: View leave type title instead of name

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php
The "Enter Name" filter wasn't working properly:
It's been fixed and refactored to consider case insensitive searches as well:
Also, when the user is in the _civihr_manager_ role, the filter will only show reportees (people that have "Line Manager" relationships with the current user).
=> Pchr 1176 ssp task block enter name filter not working

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/reports.js
This PR update:
- the datepicker identifiers to work with the newest version;
- fix the bootstrapcivicrm path which is responsible to add the SSP style;
- add a different placeholder on the input, `yyyy-mm-dd` instead of `yyyy-MM-dd`;
- add the `ng-click` directivetive on the calendar icon;
- also it was updated the code indentation on `reports.js` to uses 2 spaces.
***Before***
***After***
=> PCHR-1005: Fix datepicker

civicrm_resources/civicrm_resources.module
Problem : Stylesheets were not getting injected into Drupal through api callbacks and also the code written was not following proper Drupal coding standards.
https://compucorp.atlassian.net/browse/PCHR-949
Solution: Changed the path that was getting generated with Drupal ROOT in drupal_add_css function to remove path prefix and make that loaded like other files which are part of Drupal without Drupal ROOT path included . example it should be loaded like sites/all/modules/filename and not like https:civihr/sites/all/modules.
Fixed all the missing Drupal coding standards as we need to follow strict coding standards to make this an generic changes.
=> PCHR-920: Changed the path for loading the files.

civihr_employee_portal/civihr_employee_portal.module
The civihr_admin_theme is being deleted, so any reference to it doesn't serve any purpose anymore (and the whitelist was empty to begin with)
=> PCHR-1403: Remove reference to civihr_admin_theme

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php
The issue appears on CiviCRM 4.7 (regarding to API changes) and causes an error when using
'id' => array('IN' => array())
API parameters with empty array (while CiviCRM 4.5 works fine with it).
I've added an additional check and now there is no call executed if ID array is empty.
Also I've removed '$rowContacts' variable initialization as it wasn't used in the script.
=> PCHR-1452: Skipping API GET call on Contact if there is an empty array of Contact IDs.

civihr_employee_portal/src/Blocks/ManagerCalendar.php
On civihr-dev server there was a few of 
_Notice: Undefined offset: 62 in Drupal\civihr_employee_portal\Blocks\ManagerCalendar->generateBlock() (line 150 of /var/www/civicrm-buildkit/build/hr16-develop/sites/all/modules/civihr-custom/civihr_employee_portal/src/Blocks/ManagerCalendar.php)._
notices, caused by empty $colour_codes array for some of absence types. The absence types colours are defined in calendar_absence_list Drupal View for all default absence types. But if there are any new absence types created then the absence types don't have any default colour and this cause the issue.
I've modified ManagerCalendar class to set a default colour for an absence type if it's not set.
BTW. The colours can be managed in:
http://civihr-dev.civihrhosting.co.uk/admin/structure/views/view/calenda …
=> PCHR-1318 - Setting default colour code to '#ffffff' if it's not set in Views settings.

civihr_employee_portal/civihr_employee_portal.module
Problem: "bootstrap-civicrm-style.css" does not exist any more.
Fix: Changed it to 'bootstrap.css'
=> PCHR-1316: Modify Bootstrap filename

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/tasks.js, civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php
Tasks that had a due date of tomorrow weren't show in the "Due This Week" section of the "My Tasks" block in the SSP
This was due to the fact that the constant (`TASK_TOMORROW`) used to identify the filter type that a given task belonged to referenced an index (`5`) that didn't match any of the available filters:
```php
$taskFilters = array(
0 => 'All',
1 => 'Overdue',
2 => 'Due Today',
3 => 'Due This Week',
4 => 'Later',
);
```
because "tomorrow" tasks are not grouped in a specific section, but are put together with the "Due This Week" tasks
Initially I simply made `TASK_TOMORROW` reference the "Due This Week" index, `3`.
I thought went on and refactored this part a bit, by removing the `TASK_` constants altogether and by making the `$taskFilter` array more expressive in terms of key, …
=> PCHR-1497: Fix count of "Tomorrow" tasks in SSP block

civihr_employee_portal/civihr_employee_portal.module
With this change, any request made by an anonymous user will be redirected to the /welcome-page.
The redirection happens inside the hook_boot(), before any page has been rendered and any module has been loaded, in order achieve good performance.
The besides the welcome-page, an anonymous user must also be allowed to access the URL used when the user clicks on the "Click here to request one from your HR administrator" link.
=> PCHR-1480: Redirect non-authorized users to /welcome-page

civihr_employee_portal/views/views_export/views_hr_documents.inc
**Problem:**
Trying to search for HR Resources using a keyword would result on a blank page and a response with status code 500.
The source of this problem is the commit 8427db4c. On it, the hr_resources view was changed to load the short description instead of the body of the node, but the view's combine filter was still trying to use the old body field, resulting on the error.
**Solution**:
The combine filter was updated to use the short description field instead of the body.
Here you can see the filter working after the fix:
=> PCHR-1458: Fix error 500 when using the keywords filtes on HR Resources

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.user_permission.inc
When removing (View My Details) from a specific role , it will still be able to see ( My details ) menu and access it .
Unlike other menu items which is controlled by views , (My Details ) view menu item is defined inside civihr_employee_portal_menu and the permission is given to it was based on roles instead of permission . So I'v changed it and it can be controlled by (View My Details) permission only.
I also fixed the access arguments for (Quick Approve Leave) ajax call which used to generate emails when leave request get approved , so now emails will get generated when an absence get approved by any user with  (access manager approval screen) permission.
Finaly , I've added a new permission ( change document status ) and who have it can change documents status on SPP in case the …
=> PCHR-1398: My details menu permission fix

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc, civihr_employee_portal/views/views_export/views_my_details_block.inc, civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
The SSP Reports merge introduce a new structure to link the job contract and job role entities for views. They are now all linked through a revision.
These two views use these entities and had to have their relationships declarations updated in order to properly fetch the information. Since things are now linked though revisions, I also had to add contextual filters to the views to make sure it will return only the information related to the current revision.
I also made one small fix to the query that creates the hrjc_role view. It was joining with the option value using its ID, but recently this has changed to use the option value value. I changed the query to reflect this.
Below are the before/after screenshots of My Details and Staff Directory. Note that, on Staff Directory, we had a …
=> PCHR-1483: Fix missing job contract/roles fields on My Details and Staff Directory views

civihr_employee_portal/civihr_employee_portal.module
When viewing vacancies , the location value appear instead of its label .
That's because the location value which is retrieved with other vacancy details are not converted to label which i fixed in this PR by passing the Vacancies list to a new function **civihr_employee_portal_convert_array_option_value** that do the conversion .
=> PCHR-1245: Fix vacancy list to show location label instead of value

civihr_employee_portal/views/views_export/views_my_details_block.inc
The contextual filter for the contract period start date was filtering out records without a start date (that is, contacts without a contract), making the My Details tab empty for such contracts.
This fixes the issue by allowing an empty start date. In that case, only the information related to the contact (Name, Work email and Work Phone) will be displayed and the contract related fields will be empty.
This is the My Details block before the changes, for an user without a contract:
And this is after the fix:
For comparison, this is how it looks like for a contact which has a contract:
=> PCHR-1550: Fix My Details views to show contact details even if it doesn't have a contract

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/civihr_employee_portal.module
Removing unnecessary resource files from CiviHR pages that are not required to be loaded. 
Below files are removed from being loaded from all the CiviHR pages.
1. Removed from civihr_employee_portal_init function 
* 'civihr_employee_portal/css/custom.css'
* 'org.civicrm.bootstrapcivicrm/css/bootstrap.css'
* 'civihr_employee_portal/lib/sweetalert/sweet-alert.css'
* 'civihr_employee_portal//lib/tablesaw/tablesaw.css'
2. Removed from .info file and moved to init function
* 'js/scripts.js'
* 'js/filters.js'
* 'js/plupload/plupload.full.min.js'
* 'js/plupload-init.js'
* 'js/chart.min.js'
-; Additional js
* 'lib/tablesorter/jquery.tablesorter.min.js'
* 'lib/tablesaw/tablesaw.js'
* 'lib/sweetalert/sweet-alert.min.js'
3. Removed un-wanted contrib modules js and css 
* …
=> PCHR-1583: Removed un-wanted files from being loaded from civicrm pages

civihr_employee_portal/civihr_employee_portal.module
During the merge of the Reports branch, this button was broken and
clicking on it would throw an alert message about an ajax error:
To fix that, I copied the piece of code from before the merge that was responsible to create the link. This also fixed the link icon:
| Before | After |
|--------|-------|
| ![captura_de_tela_2016-08-26_as_00_19_45](https://cloud.githubusercontent.com/assets/388373/17993068/1dc38b9a-6b23-11e6-9108-90ad8e6b00fb.png)| ![captura_de_tela_2016-08-26_as_00_20_44](https://cloud.githubusercontent.com/assets/388373/17993071/23515e16-6b23-11e6-83c3-8358eeb14b86.png)|
=> PCHR-1457: Fix the Print Leave Report button on "My Leave" block

civihr_employee_portal/civihr_employee_portal.module
When a guest user access /user or ?q=user from the browser , it shouldn't be redirected to /welcome-page because that will prevent from logging into drupal in maintenance mode .
Before : 
After :
=> PCHR-1589: Don't redirct guest users to welcome-page from /user page

civihr_employee_portal/views/views_export/views_hr_vacancies.inc
When using filters to search for vacancy , a "no result found" message should appear to the user in case there are no results .
A No results behavior is added to vacancy list drupal view .
- Before
- After
=> PCHR-1460: Show (no result) if vacancy search shows no result

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
Updated (civihr default permissions drupal  feature) to include Access CiviHR manager approval screen for administrator, civihr_admin and civihr_manager by default .
=> PCHR-1652: Set default roles for (access manager approval scree) permission

civihr_employee_portal/views/views_export/views_hr_resource_types_list.inc
Even when Edit terms in HR Resource type permission is enabled the user cannot access http://civihr-staging.civihrhosting.co.uk/admin/structure/taxonomy/hr_resource_type/ .
But that's the default drupal behavior , having the permission will allow the user to edit the "terms" added to (HR Resource type) only , if you want to be able to access this page , then you should have (Administer vocabularies and terms) permission.
But to work around this we need to create a new drupal view that show the list of Vocabulary terms in (HR resource type) .
The new view get added (hr_resource_types_list) and another PR added https://github.com/compucorp/civihr-employee-portal-theme/pull/104 to add a link for this new view in the gear menu.
=> PCHR-1520: Add new view to show (HR resource type) Vocabulary terms

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
any user with civihr_admin should be able to access the site in maintenance mode
=> PCHR-1636: Allow civihr_admin role to access the site in maintenance mode

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.install
Problem : 
Updates hook were given in-proper naming convention under civiHR Employee Portal features module, calling civihr_employee_portal_update_7000 but it should be called as civihr_employee_portal_features_update_7000 according to https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_update_N/7.x
Above was causing issues as we already have an module named civihr_employee_portal  so while updating it was throwing 
`Fatal error: Cannot redeclare civihr_employee_portal_update_7001() (previously declared in sites/all/modules/civihr-custom/civihr_employee_portal/civihr_employee_portal.install:32) in sites/all/modules/civihr-custom/civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.install on line 141
`
Solution: …
=> PCHR-1248: Refractored update hooks naming convention.

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.info, civihr_employee_portal/features/leave_and_absences_feature/leave_and_absences_feature.features.inc, civihr_employee_portal/features/leave_and_absences_feature/leave_and_absences_feature.info, civihr_employee_portal/features/leave_and_absences_feature/leave_and_absences_feature.module, civihr_employee_portal/features/leave_and_absences_feature/leave_and_absences_feature.pages_default.inc
Problem:
Need to have simple drupal Page that can be exported in a new "Leave and Absences" feature, that will contain the block described in   PCHR-1248. Basically a bare-bone container that provides a menu link in the top menu bar and a place where the user can access the angular app.
Solution:
Created Panel page called my-leave that contains the block called my_leave which contains pre-defined template markup from block with required user access permissions "Access CiviHR Leave and Absences."
=> PCHR-1247: My Leave page build.

civihr_employee_portal/css/custom.css
Columns were not aligned correctly i.e. header table cells were wider than content table cells.
=> PCHR-1620: Align columns in absence block

civihr_employee_portal/civihr_employee_portal.module
After new user requests a login,  the reset password link received via email which looks something like this  https://compucorp.civihrhosting.co.uk/user/reset/12/1477310738/At0L5hbbyhOk-XNeXj8kQhxkGoPKMQjzayjsSBaoXwQ  Will redirect to welcome-page instead which is wrong . So any access to a link start with **user** for anymones users should not lead to welcome-page redirection .
Also  when the logged in user access /civicrm it should be redirected to T&A dashboard not to civicrm dashboard .
So I've changed  **_block_anonymous_access**  to **_user_redirection** to handle both situation
=> PCHR-1589: fix user redirection

civihr_employee_portal/civihr_employee_portal.module
Don't allow logged in users to access civicrm/dasboard by redirecting them to T&A dashboard.
=> PCHR-1698: Redirect from civi dashboard to T&A dashboard

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc
Rewriting absence_activity SQL View to base on leave activity records by leave type IDs  instead of custom absence comment table. The comment table may be empty and therefore SQL View won't create any data.
=> PCHR-1651 - Absence report doesn't pick up absence data from civi

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc
Creating a new 'civihr_employee_portal_hrreport_get_exposed_filter_default_values()' SSP function to map date filter default values to the view if the values are not specified in the request.
=> PCHR-1628 - Absence report date filter is showing no results

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/filters.js
Changed functionality of quick approve/reject buttons, so that instead of making a
direct API Call to CiviCRM, it makes the call to the Drupal civihr_employee_portal
module, where the request is processed.
- Changed quick-button functionality on front-end
- Added manager_approval/%ctools_js/quick_approval route
- Route uses civihr_employee_portal_manager_approval_quick_approval as callback
- Added _invoke_rules_on_absence_decision helper function to build required data
for rules_invoke_event
=> PCHR-1382: Fixed Quick Approve/Reject Buttons in Manager Absence Approval

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
Several issues were reported with Staff Directory view, all problems where
due to misconfiguration of parameters to generate the query for the contact
list.
1. Not all contacts shown: view was filtering contacts that either had no manager, or had a manager with the "Leave Aproved By" relationship exclusively. Solved by removing conditions from filters.
2. Managers not listed at all: relationship to contacts table for manager was not configured.  Fixed by adding relationship and associating field to relationship.
3. Manager filter not working: as with problem number 2, relationship was not configured, hence filter could not be used.
4. Ajax error when searching name: problem reported to occur when a nameless contact was present on result set.  Unable to replicate, but tested and works ok. …
=> PCHR-1609: Fixed Problems on Staff Directory View

civicrm_resources/civicrm_resources.module, civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module, civihr_employee_portal/civihr_leave_absences/templates/my_leave.html
This PR complements the work done in [this PR](https://github.com/civicrm/civihr/pull/1255), so that the L&A AngularJS app defined in `uk.co.civicrm.hrleaveandabsences` can be used in the */my-leave* Drupal page
The `civicrm_resources` module was adding the javascript files in the `<head>` of the page. The behaviour has been changed so that now it adds the file right before the closing of the `<body>` tag
```php
drupal_add_js(/* ... */,  array('scope' => 'footer'));
````
By using the `civicrm_resources` module, both the `reqangular.min.js` (which contains RequireJS, AngularJS and all the common angular dependencies) and the `my-leave.min.js` (which contains the `my-leave` angular app) are added the the `/my-leave` page
```php
civicrm_resources_load('org.civicrm.reqangular', …
```
=> PCHR-1250: Set up the AngularJS app

civihr_employee_portal/civihr_leave_absences/templates/my_leave.html
The civihr-employee-portal drupal module holds the current user's CRM id in `Drupal.settings.currentCiviCRMUserId`.
The my-leave angular app expects this value in the CMS-agnostic `CRM.vars.leaveAndAbsences` object
In this PR we simply pass the value from one variable to another
=> PCHR-1283: Pass current user CRM id to my-leave angular app

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module, civihr_employee_portal/civihr_leave_absences/templates/manager_leave.html
Problem :
Added Manager Leave block that can fetch custom markup from pre-defined template file and also an angular js app defined for Manager Leave block that will be use to place block in whatever page/view is necessary.
Solution:
Created new block called Manager Leave that contains markup for block from pre-defined template file and angular js app. As this is custom block we can easily export and place in whatever region we require.
=> PCHR-1792: Added Manager Leave block containing AngularJS app.

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc, civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
**Issues with Departments**
When a contact in staff directory has roles in different departments, these are shown as comma separted values in staff directory. If you search by a specific department, although the search result shows the correct staff, department column shows only the department you searched for, regardless of how many departments each contact is in. Also, department column is showing values from all past job roles too.
Fixed by adding a department_list column to hrjc_details view in CMS database, so that a department list for active roles of that contact's contract/revision is always shown, despite filtering of specific roles trough searchable role fields.
Also updated view to show new department_list field in results, and to include only active roles in all queries. …
=> PCHR-1767: Fix Staff Directory Problems with Locations and Departments

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
In order to be able to check permissions on the frontend code, we need to make civi export them to the global CRM.permissions global javascript var. This can be done by passing a list of permissions to the `CRM_Core_Resources::addPermissions()` method, which is called on the hook_init() implementation of the "CiviHR Leave and Absences" Drupal module.
The exported permissions are:
- access leave and absences
- administer leave and absences
- access leave and absences in ssp
- manage leave and absences in ssp
=> PCHR-1818: Push the L&A permissions to the global CRM.permissions var

civihr_employee_portal/civihr_leave_absences/templates/manager_leave.html
This PR contains the following basic setup for Manager Leave page,
1. `<ui-view>` - This would be replaced by Angular's views.
2. `CRM.vars.leaveAndAbsences. baseURL` - Base URL for the LeaveAndAbsences extension saved in this global variable.
3. `CRM.vars.leaveAndAbsences. contactId` - `contactId` for the logged in user is saved in this global variable.
=> PCHR-1797: Manager Leave HTML

civihr_employee_portal/civihr_employee_portal.module
IF you go to www.any-civihr-site-url.com/ then the emergency contacts webform will appear. but what is expected to happen : 
1. If you have 'access civicrm' permission: get to T&A dashboard
2. If you don't have 'access civicrm' permission: get to /dashboard
Removing hook_boot implementation and moving _user_redirection() call to hook_init where user_access() function is accessible . Then altering   _user_redirection() so if the $current_path == '' (which is any empty string that means we are on the main site path / )  then we redirect according to the specified rules above.
=> PCHR-1719: Redirect logged-in users from the main path (/) to their acessible dashboard

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
Users with civihr_admin role should be able to create drupal user records for contacts, using the appropriate option in the "Actions" menu of the contact view, but the option is currently not shown.
Permission being checked to show link to create user record is "administer users", which was disabled for civihr_admin role by default.  Fixed by adding permission for the role in civihr_default_permissions feature.
=> PCHR-1754: Add Administer Users Permission to civihr_admin Role

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/css/custom.css
A function was required to return the current version of civihr to display on the footer.
The footer was styled to meet the design requirements.
=> PCHR-1685: update footer info

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
Problem:
SSP reports pull values instead of labels for Contract Normal place of work field value.
Solution:
1. Reports are shown using CiviHR Reports - People view & CiviHR Report - Leave and Absence, Reports were showing Contract Normal place of work id because it was shown using wrong field type called location.
2. Changed field to Location Label that pulls the Label  ( Contract Normal place of work ) and displays accordingly on Reports page.
Before:
After:
=> PCHR-1857: Changing view field to show Location label for Reports page.

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
Report data picks up only staff with active job contract and active role at the same time. If that staff has no roles, or past or future role, they are not picked up in reports data.
1.As the result should include those have active Contract and should not be dependent on any kind of Role entity status we need to remove Role (HRJobContract Role entity) HRJobContract Role entity: Role start date and (HRJobContract Role entity) HRJobContract Role entity: Role end date Contextual Filters validation from view because it always checks for dates of Role regardless of any type of Contract attached to entity so even if people has Active contract and no Active Roles attached it won't show on people list.
2.Removed (HRJobContract Role entity) HRJobContract Role entity: Role start date and …
=> PCHR-1889: Removing Role contextual filter validation for Reports.

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc, civihr_employee_portal/views/views_export/views_my_details_block.inc, civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
E-mail and phone data shown on My Details view and Staff Directory view was being queried from database using ID's for location that were hard-coded on the views.  This meant if the ID's changed for any reason, information for contacts was lost on those views.
Fixed by creating a CiviHR entity built on a database view that queries work and home e-mail and phone information using location names instead of ID's.
=> PCHR-1764: Get Staff Contact Information by Location Name

civihr_employee_portal/views/includes/civihr_employee_portal_handler_absence_table_header_block_area.inc
Toil credits (and all leave credits, for that matter), where being subtracted from entitlement balance in dashboard My Leave block, instead of being added.
Fixed by conditionally adding/subtracting amount of days in leave request, depending on if its a credit or debit to entitlement.
=> PCHR-1944: Add Toil Credits to Balance in Dashboard's My Leave Block

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
Content in welcome page holding logo, site name and slogan was being included using a custom module with the raw HTML left to be edited to update any information, which is not ideal if it is supposed to be administered by regular users.
Removed custom block and added separate blocks with administrable drupal site logo, site name and slogan to the page.  Each block has its own CSS ID, so each can be styled to match expected look & feel for welcome page.
=> PCHR-1712: Improve Administration of Content on Welcome Page

civihr_employee_portal/civihr_employee_portal.module
**Problem**
In civihr after login you always get redirected to T&A dashboard (if you are admin) or SSP (if you don't have access civicrm permission) as required.
This should only happen when entered URL was /. In other cases after successful login user should be redirected to the URL they tried before login page redirect.
**Solution**
Added destination parameter to _user_redirection function that redirects depending upon the user state and permissions. And after login it should redirect to last page they navigated from thats handled using hook  user login function to route to required destination after checking permissions for that page and user.
=> PCHR-1870: Adding destination parameters while user login and redirection.

civihr_employee_portal/js/reports.js, civihr_employee_portal/views/civihr_employee_portal.views.inc
Length of service in people reports was being shown in number of days since start date of contract. 
Pivot table :
Implemented human readable format: "%y years %m months %d days", using civihr_employee_portal_views_pre_render hook. Each part of the interval is used only if it is more than zero.  Plurals and singulars for years, month and days are also taken into account in final rendering of length of service.
For Pivot table: its has been handled using updateFilterbox function under report.js to update length of service to proper format.
Pivot table :
=> PCHR-1782: Use Human Readable Time Intervals for Length of Service

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/src/Forms/AbsenceRequestForm.php
On undetermined occasions, trying to add a leave request will show an error message saying "This date period is not yet defined", even if the period for the given start date is properly defined.
Validation of leave request start dates against configured periods in CiviHR is done using data stored in drupal cache, which is built the first time a date is validated and expires every 6 minutes.  Watchdog log calls were added when setting and retrieving the data to cache, and on validation failure of leave request start date, to gain further inisght on the problem and plan a proper solution.
=> PCHR-1976: Log State of Periods Cache on Start Date Validation of Leave Request

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module, civihr_employee_portal/civihr_leave_absences/templates/manager_leave.html, civihr_employee_portal/civihr_leave_absences/templates/my_leave.html
In order to upload files in CiviCRM using the Attachment API and the related callback URL (civicrm/ajax/attachment), we need to pass along an attachment token. This token is created in the backend, using the `CRM_Core_Page_AJAX_Attachment::createToken()` method, but it's not available in the frontend where it's required to send the upload data.
Uploads are necessary to add attachments to the Leave Requests. This can be done in 2 places of the SSP: The "My Leave" and the "Manager Leave" pages. So we need the token available in both.
In `civihr_leave_absences_init()`, the attachment token is added to the Drupal settings. In `my-leave.html` and `manager-leave.html`, we fetch the info from the Drupal settings and add it to `CRM.vars.leaveAndAbsences.attachmentToken`
=> PCHR-2075: Make the attachment upload token available in the "My Leave" and "Manager Leave" pages

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
**Problem:** 
Reqangular js file was getting loaded twice from my-leave and manager_leave pages that was getting called from generic function because of this it was throwing below console errors.
**Solution:**
Removed loading of Reqangular js file twice from civihr_leave_absences_get_markup function.
=> PCHR-1953: Removed loading of reqangular.js file twice.

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_role.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
**Task**
Create civihr_admin_local role for all the new and existing civihr sites as the new default role with required permissions from page https://compucorp.atlassian.net/wiki/display/PCHR/Drupal+permissions+configuration.
**Solution**
1. Created role using hook_update to add to existing sites with the required permissions packaged into default_permissions feature module.
2. For adding new role for all the new civihr sites its handled using buildkit hr16 config https://github.com/civicrm/civicrm-buildkit/pull/303.
=> PCHR-1975: Added new role civihr_admin_local and updated required permissions.

civihr_employee_portal/civihr_employee_portal.module, civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
The Absence Activity view was picking data from the HRabsence extension related tables but since the extension will soon be deprecated in favour of the Leave and Absence extension, 
This PR makes the change by modifying the query to build the Absence activity view to pick data from L&A related tables.
The Leave and Absence report view now has its data populated from L&A tables although some view handlers need to be updated as some of the columns are showing incorrect values the columns are Absence status (Picking statues from HRabsence leave request statuses), Absence Duration In Days, Absence Amount Taken, Absence Amount Accrued, Absence Absolute Amount . This will be fixed in subsequent PR's.
Here is a sample cross-section of the Leave and Absence Reports Page.
=> PCHR-2120: Rewrite the Query to build Absence Activity View to pick data from L&A related tables

civihr_employee_portal/tdd/HelperFunctionsTest.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
A contextual filter was added to ensure only active roles are shown [in a previous ticket](https://compucorp.atlassian.net/browse/PCHR-1767). This had the side effect of only showing users with active roles in the staff directory.
The desired logic is to show all users with an active contract regardless of roles. We only care about the role if filtering by department.
In addition the rules for what to show have changed:
- Instead of showing contract title we show role titlles
- Instead of showing contract location we show role locations
Also a bug where managers with relationships starting in the future was fixed as part of this.
- Remove the contextual filter for role end.
- Add a hook to add this filter only if the department filter is set
- I wasn't sure where to put the …
=> PCHR-1890: Fix filtering on staff directory

civihr_employee_portal/civihr_employee_portal.module
Previously, the Absence status views handler for the L&A reports view fetches statuses from an option group related to the HRabsence extension. 
This PR modifies the function that fetches the statuses to fetch from the hrleaveandabsences_leave_request_status option group.
=> PCHR-2122:  Update The Absence Status Views Handler to fetch statuses from Leave Request Status Option Group

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.rules_defaults.inc
The 'request access' e-mail that is sent to site admins does not contain a link to the site
Add a link to the `admin/people` page inside the email
`drush fr -y --force civihr_employee_portal_features.rules_config` must be run to update rules
=> PCHR-2039: Add link to people page in employee access request email

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_email.inc, civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
The staff-directory view currently uses the primary email, regardless of whether it is personal or not. It should use only the work e-mail(s) and be blank if there are none.
In addition, rendering a list of emails will show them as plain text unless the `civicrm_handler_field_email` is used. However, this handler does not support multiple e-mails - for example 'a@gmail.com b@gmail.com' will result in `<a href="a@gmail.com b@gmail.com">a@gmail.com b@gmail.com</a>`
Change the view to use an existing field, the 'work_email' field defined on the `hrjc_contact_details` table. This field will be empty if there are no work emails, or a list of them (space separated) if there are some.
In order to render them properly with the links I added a new custom field handler that will make links from …
=> PCHR-2105 Restrict to Work Emails in Staff Directory

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Adds a pull request template.
Each creator of a pull request defined their own structure for the description.
This template will be used as a suggested format for the description.
To see what the PR template looks like now check [here](https://github.com/civicrm/civihr/blob/PCHR-2159-pull-request-template/.github/PULL_REQUEST_TEMPLATE.md)
---
=> PCHR-2159: Add Pull Request Template

civihr_employee_portal/views/includes/civihr_employee_portal_handler_absence_table_header_block_area.inc, civihr_employee_portal/views/templates/views-view-table--Documents--block-1.tpl.php, civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php, civihr_employee_portal/views/views_export/views_documents.inc
The document and document manager widget s are hidden on the SSP dashboard if you don't have documents assigned to you. They should always be shown, with a message saying there are no documents.
If you didn't have documents assigned you wouldn't see the "Documents" or "Document Manager" widgets.
You will always see the "Documents" and "Document Manager" widgets, regardless of whether you have anything assigned to you.
This PR makes changes to a view so reverting the view will be necessary.
Changing the view was a small issue, but the template does not expect empty results so I needed to fix the warnings from PHP.
---
It looks like the tests haven't been run for a while and are broken.
=> PCHR-2143: Always Show Documents Widgets

civihr_employee_portal/civihr_employee_portal.module
When the Leave and Absence civiHR extension is disabled/uninstalled, the Leave manager can still see Manager Leave and My Leave page on the SSP. The reason is that it is the Employee portal module that creates the permissions that is needed to see this pages. This PR removes these permissions from the Employee portal module so that L&A extension can create these permissions itself.
The permissions are added to be created from L&A extension [here](https://github.com/civicrm/civihr/pull/1892).
The Employee portal module creates the permissions for accessing Manager Leave and My Leave page on the SSP.
The Employee portal module no longer creates the permissions for accessing Manager Leave and My Leave page on the SSP.
Not sure how to run the tests on the module, besides didn't change …
=> PCHR-2196: Remove permissions for accessing my leave and leave manager page on SSP

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info, civihr_employee_portal/js/ta-documents-app.js, civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
Currently in the view of Documents Widget in SSP, modal is displayed using `ctools`. And this needs to address latest requirements to New Document Modal as in T&A. for this an angular app needs to be injected to the view. Also with reusing the modal form T&A, respective fields are to be hidden for the 'staff' role.
1. Pass 'staff' as role to second argument to 'modalDocument(id, role)' in  `views/templates/views-view-table--Documents--block.tpl.php` which will be passed to Modal Document Controller in T&A through `modalDocument()` in `js/ta-documents-app.js` and using the role to hide the respective fields in the document modal in file `uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html`
2. The angular app injected in the SSP was created originally to work only on the …
=> PCHR-2144: Updates to SSP documents widget

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
All users in CiviHR should have the 'Change own username' permission enabled by default.
Only roles that had the permission enabled by default were administrator and civihr_admin_local.
Roles with 'Change own username' permission are administrator, civihr_admin, civihr_admin_local, civihr_manager and civihr_staff.
=> PCHR-2266: Add 'Change Own Username' Permission to CiviHR Roles

civihr_employee_portal/js/ta-documents-app.js
As the document modal is reused form T&A, the document modal now requires `modalMode` to initialize modal title in T&A. So, the modal mode needs to be passed while opening document modal.
1. `modalMode` is passed to modal options as `''`(empty) because in SSP, the modal title is not dependent on `modalMode` as we are displaying the modal title as document type. We need to  pass the `modalMode` just to make `modalMode` be available in Document Modal Controller in T&A in file `uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js`.
```js
function openModalDocument(data, role) {
var modalInstance = $modal.open({
...
resolve: {
modalMode: function () {
return '';
},
...
}
});
};
```
No tests written for ssp.
=> PCHR-2319: Pass modalMode to Document Modal resolve option

civihr_employee_portal/js/ta-documents-app.js, civihr_employee_portal/views/templates/views-view-table--Documents--block-1.tpl.php, civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
This PR is for the hot fix to add name space to temporary styles for the document modal in ssp for staff and manager document sections.
Previously, modal in request leave was broken ad follows:
After name-spacing the temporary styles, the leave request modal looks ok
1. In file `civihr-custom/civihr_employee_portal/js/ta-documents-app.js` change the modal option to attach the modal in the root element as follows:
```js
function openModalDocument(data, role) {
var modalInstance = $modal.open({
**appendTo: $rootElement,**
...
});
}
```
2. Name-spacing the temporary styles for document modal in ssp in file `civihr_employee_portal_theme/civihr_default_theme/scss/base/_task-assignments-modal-temp.scss` 
```css
[data-ta-documents],
[data-ta-documents-manager] {
// All temporary styles for …
```
=> PCHR-2317: Attatch document modal to the root of angular app

civihr_employee_portal/js/ta-documents-app.js, civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
During the Document Updates in SSP, angular app was created and injected in SSP which added additional `#/` in the url causing the following error on opening modals.
1. Added following code in `civihr_employee_portal/js/ta-documents-app.js`:
```js
(function(angular) {
angular.module('taDocuments', ['civitasks.appDocuments', 'civitasks.directives'])
.config(function ($urlRouterProvider, $locationProvider) {
$locationProvider.html5Mode(true); // This is required to remove # for the URL
$urlRouterProvider.otherwise('/dashboard');
})
...
})(angular);
```
This code will be removing the `#/` form the url and add a fallback url to be `/dashboard`.
2. Add `<base href="/"> ` in file `civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php` which applies the base path to …
=> PCHR-2318: Buttons change and console error when modal is open on ssp

civihr_employee_portal/views/templates/views-view-table--Documents--block-1.tpl.php
Currently, while displaying the selected  status on Document manager in ssp, whether  to display  a status as selected is determined by comparing status id and status value, which is never true. so the status never gets selected.
1. Since the value of `$content` is string value like `awaiting-approval`. So, modifying to compare status value to the status content, rather than status_id with status content. 
From:
```php
if ($statusKey == (int) strip_tags($content)):
$selected = ' selected="selected"';
endif;
```
To:
```php
if (strtolower($statusValue) == strip_tags($content)):
$selected = ' selected="selected"';
endif;
```
2. Display the status in Sentence format rather than all lowercase:
```html
<option value="...><?php print ucwords($statusValue);?></option>
```
No added tests
=> PCHR-2243: Compare status value with content instead of status id

civihr_employee_portal/views/includes/civihr_employee_portal_handler_documents_date.inc
The issue is  the value for (Expiry date) " $value" will be "null" when a document is created without expiry date. And the while formatting the expiry date  for  such documents , "null" becomes "1 Jan 1970".
1. Change following code in file `civihr-employee-portal/civihr_employee_portal/views/includes/civihr_employee_portal_handler_documents_date.inc`
```php
class civihr_employee_portal_handler_documents_date extends views_handler_field {
function render($values) {
$value = $this->get_value($values);
return date('M d Y', strtotime(strip_tags($value)));
}
}
```
To
```php
class civihr_employee_portal_handler_documents_date extends views_handler_field {
function render($values) {
$value = $this->get_value($values);
if($value) {
return date('M d Y', strtotime(strip_tags($value)));
}
}
}
```
- …
=> PCHR-2329: Format expiry date if it only exists

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/views/views_export/views_documents.inc
Document Manager block on SSP Dashbord is used to show the list of documents they have assigned. A document can be assigned to several managers, however, only the first manager assigned was able to see the document on Document Manager block.
The problem arose because the DB view being used to build the manager block was grouping results by document ID, thus only one manager was shown in result set.
Fixed by altering the SQL being used to build the DB view, adding assignee id to GROUP BY fields. Also had to fix the Documents Dashboard Block, since the new structure of the DB view caused each document to be shown several times (one time per each assigned manager). Did this by merging multiple results within the Drupal view.
List of documents in SSP dashboard showed an empty type for every …
=> PCHR-2333: Show Documents to All Assignees on Document Manager

civihr_employee_portal/views/views_export/views_documents.inc
The previous fix for PCHR-2333, merged into staging branch on [this](https://github.com/compucorp/civihr-employee-portal/pull/318) PR, was making all documents to be merged into a single row. 
All fields on the view's display were being merged using 'merge unique values' option.
Fixed by altering merge configuration of the view, assigning the 'filter' option on merge option for Document ID field, so different rows are shown per unique document ID.
=> PCHR-2333: Fix Document Dashboard Block

civihr_employee_portal/js/ta-documents-app.js, civihr_employee_portal/views/templates/views-view-table--Documents--block-1.tpl.php, civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
After the completion of #312  , there was a issue with spinners in both document and document manager section in ssp. i.e when clicked "open" in any one on the document, the spinner is displayed in all of the documents. This PR fixes the spinner to be displayed to only specific document.
The spinner is displayed to each document in the list.
Displays spinner to the only sepicific document in the list
1. Call following in "civihr-custom/civihr_employee_portal/js/ta-documents-app.js"
```js
$rootScope.$broadcast('ct-spinner-show', 'document-' + id);
``` 
to display the spinner in ssp document.
2. Add following 
```html
<td ct-spinner ct-spinner-id="document-<?php print strip_tags($row'id');?>">
``` 
in open button holding table column. in both file …
=> PCHR-2354: Spinner in ssp does not look right

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/js/ta-documents-app.js
Currently, when trying to save the documents form Documents Widget in SSP. A error  is thrown because date format is not configured for angular app in ssp for documents modal.
When a `civihr_manager` changes the status form the documents widget in ssp, the status does not get updated and displays the access denied 403 error. Which was due to the permission issue.
1. Cannot save document by the civihr_manager in ssp
2. Changing status does not get saved in documents manager in ssp
1. 'civihr_manager` can save edited document form ssp
2. `civihr_manager` can changed the document status and it gets saved
1. Configure date format for SSP in mini angular app for the Document modals.
```js
.controller('ModalController', ['$scope', ..., 'settings', 'DateFormat',
function($scope, ..., settings, …
```
=> PCHR-2355: Configure DATE_FORMAT in HR_settings for SSP

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
When a contact had an inactive role/relationship and one or more active ones, inactive roles/relationships were being removed. This sometimes caused the directory to render the list of roles with a comma inserted before the actual list of roles (eg. ", Role 1, Role 2, ...").
When a contact had an inactive role/relationship and one or more active ones, inactive roles/relationships were being removed from the result set with a hook that altered the value for the field, by setting it to null. If the inactive role/relationship was the first role in the result set, this caused the directory to render the list of roles with a comma inserted before the actual list of roles (eg. ", Role 1, Role 2, ...").
Fixed by adding filters to the view, to check for roles with start date in the past or null, …
=> PCHR-2129: Remove Unneeded Commas From Roles in Staff Directory

civihr_employee_portal/templates/civihr-employee-portal-civihr-report-settings-age-group.tpl.php
As part of this PR `table` class is added to the `age-group` table.
The `age-group` sections table did not have `table` class and because of that the bootstrap styles were not getting applied. Added the same.
=> PCHR-2417: Add table class

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc, civihr_employee_portal/js/ta-documents-app.js, civihr_employee_portal/views/civihr_employee_portal.views.inc
The idea is to move "My Tasks", "Documents" and "Documents Manger" from the SSP dashboard to a new page, "Tasks and Documents", accessible via a new item on the main menu.
"My Tasks", "Documents" and "Documents Manger" widgets were part of SSP dashboard.
New page has been created, with the three required blocks in it, and a new menu item linking to it is shown on the main menu.
Some JS libraries were being added to dashboard page manually through the backend to enable angular and modal dialogs on the My Tasks View, so I had to add these to the new page and tweak ta-documents-app.js file so it used the new tasks-and-documents URL path.
=> PCHR-2325: Add Tasks and Documents Page

civihr_employee_portal/views/civihr_employee_portal.views.inc
Vacancies list on SSP was showing HTML tags on its description, after clicking on "More details".
Vacancy list view was showing HTML tags in every vacancy's description. This happened because HTML special characters like '<' and '>' were being changed for HTML entities '&lt;' and '&gt;' respectively, breaking the HTML.
Fixed by implementing the _views_post_render hook, replacing the HTML entities for their corresponding characters.
=> PCHR-245: Decode HTML Tags in Vacancy Description

civihr_employee_portal/civihr_employee_portal.module
Currently, when the CiviCRM notification is used in SSP, the notification does not appear as in civiCRM pages due to the reason that SSP does not have the template and styles  for the notification. This PR adds  the required `jquery.notify.js` library and fixe x the dependencies between then by re arranging the `js` files to be loaded in SSP.
- Displays the target contact in disabled dropdown
- Displays the notification in default javascript alert
- Displays target contact in plain text:
- Displays the error notification as in CiviCRM pages:
1: Add `hook_coreResourceList` in file "/civihr_employee_portal/civihr_employee_portal.module"to add the `jquery.notify.js` and rearrange the  `js` files to be loaded in the SSP page.
```php
/**
* Implements hook_coreResourceList
*
* @param array …
```
=> PCHR-2309: Target contact and notification shown wrong in SSP

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_sickness_reason.inc, civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc
Currently the Leave and Absence report on the SSP does not have sickness reason as one of its columns. This PR adds the Sickness reason column and this also makes the sickness reason available in the Pivot table.
---
Didn't run the tests in employee portal module.
=> PCHR-2449: Add Sickness reason to Leave And Absence Report

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
On https://github.com/compucorp/civihr-employee-portal/pull/323, a new page was added to the SSP. To make sure this page would be added to every existing and/or new site, the civihr_employee_portal feature was updated. However, the update was done manually, which is now causing two problems:
- The features module now considers this as being overridden
- Some refactoring was added (https://github.com/compucorp/civihr-employee-portal/blob/6979893824369990efdadce82504ac64da8b9b2c/civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc#L11-L14) with the intent of making the code more readable. This caused a lot more changes to the file than what was really necessary and it's now hard to sync 1.7 with it (due to a big number of merge …
=> PCHR-2325: Remove custom code from civihr_employee_portal features

civihr_employee_portal/civihr_employee_portal.module
A new menu under account is to be added calling "User Guide" in SSP.
Not added User guide Menu
Added User guide Menu
1. 
```php
/**
* Implement hook_preprocess_page
* @param $vars
*/
function civihr_employee_portal_preprocess_page(&$vars) {
...
$user_guide_link = '';
$image_url = $base_url . '/' . drupal_get_path('module', 'civihr_employee_portal') . '/images/profile-default.png';
if (isset($_SESSION['CiviCRM']) && $user->uid) {
...
$user_guide_link = l('<i class="fa fa-book"></i>' . t('User guide'), 'http://civihr-documentation.readthedocs.io/en/latest/self-service-portal/login-screen/', array('html' => true));
...
$vars['user_guide_link'] = $user_guide_link;
}
```
=> PCHR-2358: Add user guide link to be used in account menu

civihr_employee_portal/civihr_leave_absences/templates/manager_notification_badge.html, civihr_employee_portal/civihr_leave_absences/templates/waiting_approval_notification.html
As part of this PR
1. The html file name has been changed to `manager-notification-badge.html` because the module to be loaded is  `manager-notification-badge` and not `pending-leave-request`.
2. Added markup.
=> PCHR-1972: Changed html file name

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
The idea was to move "My Tasks", "Documents" and "Documents Manager" blocks from the SSP dashboard to a new page, "Tasks and Documents", accessible via a new item on the main menu. This was done on a previous PR (#323), however, the HR Resources Block was also added to the new Tasks and Documents page. This widget should only appear on dashboard page.
HR Resources block was appearing on Tasks and Documents page.
The block was removed from Tasks and Documents page.
=> PCHR-2325: Remove HR Documents Block From new Tasks and Documents Page

civihr_employee_portal/js/reports.js
As part of this PR, Pivot Table styles has been fixed.
As part of https://github.com/compucorp/civihr-employee-portal-theme/pull/168, `chr_custom-select` class was removed because `crm_custom-select` already existed for the same purpose. But the class for Pivot table was not updated. 
1. Class name updated to `crm_custom*`
2. Necessary markup added for the dropdown arrow.
---
=> PCHR-2326: Fix Pivot table styles

civihr_employee_portal/js/ta-documents-app.js
This PR adds the fix to implement controller as syntax for modal document controller.
1. Add 'controllerAs` attribute for document modal controller,
```js
function openModalDocument (data, role) {
var modalInstance = $modal.open({
appendTo: $rootElement,
templateUrl: config.path.TPL + 'modal/document.html?v=3',
controller: 'ModalDocumentCtrl',
controllerAs: 'documentModal',
resolve: {
// ...
}
});
}
```
2. Done some refactoring to adopt new angular js guide.
=> PCHR-2378: Use controllerAs for modal + refactoring

civihr_employee_portal/src/Security/PublicFirewall.php, civihr_employee_portal/tdd/PublicFirewallTest.php
After updating the version of the `yoti` module it's not possible to login using yoti anymore. The version of the module uses a different callback URL, which cannot be accessed by anonymous users.
Update the list of URL on the `PublicFirewall` to allow anonymous access to any URL under `/yoti/`
=> PCHR-2485: Update yoti callback URL for public access

civihr_employee_portal/src/Security/PublicFirewall.php, civihr_employee_portal/tdd/PublicFirewallTest.php
After the [update and the change of the callback URL to `yoti`](https://github.com/compucorp/civihr-employee-portal/pull/338), the module still uses the `yoti-connect` URL after the login. Since it's not publicly accessible anymore, the login won't work.
The `yoti-connect` URL was added to the `PublicFirewall` again
=> PCHR-2485: Allow yoti-connect public access again

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
Users with the `administrator` role couldn't access any of the reports under Absences -> Absence Report. This happens because the default set of permissions for this role doesn't include those necessary to access the reports.
The `administrator` roles didn't have the required permissions to access the reports:
- access CiviReport
- access Report Criteria (this one was also added to the `civihr_admin` role)
The `administrator` role has all the required permissions to access the reports.
Even though the `administrator` role is one level above the the `civihr_admin` role, it was missing some of the permissions set for the latter. The missing permissions are:
- People Management: delete in People Management
- People Management: administer People Management
- People Management: access my …
=> PCHR-2499: Add default report permissions to administrator

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
Users with the `administrator` role couldn't access any of L&A screens on the CiviHR admin. This happens because the default set of permissions for this role doesn't include those necessary to access the said screens.
The `administrator` roles didn't have the required permissions the L&A screens on CiviHR admin:
- administer leave and absences
- access leave and absences
The `administrator` role has all the required permissions to access all the L&A screens on CiviHR admin.
There was a problem with the civihr_default_permissions feature where it was not keeping track of the `administer leave and absences` permission. It was probably something that was missed during one of the syncs with 1.6, since this is something that was correct on the …
=> PCHR-2499: Add L&A default permissions to administrators

civihr_employee_portal/civihr_employee_portal.module
Yoti module name had been updated from yoti_connect to yoti because of which the login link on user profile page was not working. Updated module name to check with new name.
Changed
```php
module_exists('yoti_connect') to  module_exists('yoti');
```
---
=> PCHR-2526: Updated yoti module name for user profile page.

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
Since the functionality offered by the hrvisa and hrident extensions is planned to be replaced by the improved documents feature these extensions are not required going forward. However, as they are potentially used by existing clients we will not remove them from the code.
The staff directory view contains a filter that depends on the hrvisa extension.
The staff directory filter for visa is removed.
---
What's broken is still broken, what was working is still working :unamused:
=> PCHR-2493: Remove filter based on hrvisa custom group table

civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
Removes the JS code (`javascript:;`) from `href` as its a bad practice. And it causes the console error on clicking the Document Type in ssp document list (see before section)
- shows console error
- Does not show the console error
=> PCHR-2489: Remove JS code form href as its a bad practice

civihr_employee_portal/js/ta-documents-app.js
In SSP at the Task and Documents page we display a spinner until we get all the documents (target and assignee contact and are cached). That's why the spinner is displayed before "open" button is displayed.
The problem is it takes too long to load the data since we are currently collecting contacts form all documents. This PR fixes it by doing the following things:- 
- Displays the spinner in the button until we have at least one contact.
- The contacts for the document are cached once we click open document modal button.
1. Takes more time to fetch and cache the contacts in the document displaying spinner longer in place of open button.
1. Displays the spinner in place on button till we have at least one contact in SSP i.e current logged in contact.
1. Remove code to get all the …
=> PCHR-2457: Document open buttons take very long to load on ssp

civicrm_resources/civicrm_resources.module, civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/views/templates/views-view-table--Documents--block.tpl.php
This PR adds the fix applied in [this link](https://github.com/compucorp/civihr-employee-portal/commit/c16bbca577c72486c645f60fdff0d0588b38e2e5) by modifying the `civicrm_reource.module` file in 1.6 site. And use it to load the resources as required in appropriate section in in `civihr_employee_portal.module`.
As a result the `angular is not defined error` is also fixed in 1.6 site.
- The resources were not loaded correctly in right section causing the reqangular.min.js to load after the `ta-documents-app.js` in SSP causing angular is not defined console error as a result yoti login is also not working.
- `angular is not defined` error is not gone and SSP `/tasks-documents` has not console error.
- Document modal loads correctly in ssp, without error.
-  `/welcome-page` loads with no …
=> PCHR-2327: Divergence with civicrm resources in civi hr v1.6 and civi hr v1.7

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/civihr_employee_portal.rules.inc, civihr_employee_portal/src/Forms/AbsenceRequestForm.php
It was not possible to request leave if one of the request dates were the start or the end of the Daylight Saving Time in the timezone of the current user, set in Drupal. Whenever someone tried that, the system would return a server error and the list of dates in the Leave Request modal wouldn't be updated.
The reason was that in some places in the SSP code was required to add 1 day to a date. This was implemented with a logic that would convert the date to a unix timestamp and then add 86400 seconds to it (the number of seconds in a day), which works fine for days with 24 hours. However, in countries/timezones with Daylight Saving Time, we can have days with 25 or 23 hours, that will make the code fail.
In 2017, for example, the UK Daylight Saving Time ends on 29th Oct. This day has 25h …
=> FAR-198: Allow requesting leave for dates matching the end/beginning of Daylight Saving Time

civihr_employee_portal/views/views_export/views_appraisals.inc
When we create a new site, using buildkit, there's an Appraisal item available in the SSP menu. The appraisal extension is not complete and hasn't been released yet, so the menu should be hidden.
The Appraisals item is visible in the SSP menu:
The Appraisals item isn't visible in the SSP menu anymore:
---
No tests are affected by this
=> PCHR-2755: Hide the Appraisals menu

civihr_employee_portal/views/civihr_employee_portal.views.inc
An issue was reported on the 1.7-staging site, where it was not possible to edit "My Details" on the SSP dashboard. Whenever the button was clicked, the edit modal wouldn't open. Besides that, it was possible to see this error in the browser's javascript console:
```
scripts.js?oxo336:32 Uncaught TypeError: Cannot read property 'Modal' of undefined
at HTMLAnchorElement.<anonymous> (scripts.js?oxo336:32)
at Function.each (jquery.min.js?v=1.8.3:2)
at $.fn.init.each (jquery.min.js?v=1.8.3:2)
at scripts.js?oxo336:29
at dispatch (jquery.min.js?v=1.8.3:2)
at u (jquery.min.js?v=1.8.3:2)
```
The reason was that the modal.js file from the Ctools module wasn't being loaded. After an investigation, I found that the error started after we disabled the `Appraisals` view on the site …
=> PCHR-2759: Include the ctools modal JS for the My Details block

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
The local admin shouldn't have permission to assign all roles.
The local admin had permission to assign all roles.
The local admin does not have permission to assign all roles.
---
Same as usual, some working, some not. All tests should be working again when #346 is merged.
=> PCHR-2559: Remove "assign all roles" permission from local admin

civihr_employee_portal/civihr_employee_portal.module
All the data and the markup that was used to build the user menu in the top menu of the SSP is now owned by `CRM_HRCore_UserMenuMarkup` (see https://github.com/civicrm/civihr/pull/2236), so we don't need the `civihr_employee_portal_preprocess_page` hook anymore
Related PRs:
* https://github.com/civicrm/civihr/pull/2236
* https://github.com/compucorp/civihr-employee-portal-theme/pull/250
=> PCHR-2621: Remove hook_preprocess_page implementation

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
This PR applies the "Access CiviCRM developer menu and tools" permission (see https://github.com/civicrm/civihr/pull/2242) to the administrator role by default, for existing and future sites
=> PCHR-2628: Assign new permission to root user by default

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc
Simply renames the "Tasks and Documents" page and menu item to "Tasks
=> PCHR-2756: Rename 'Tasks and Documents' to 'Tasks'

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
This PR simply exports the menu items of the SSP main menu with the new attributes that define the FowAwesome icons (see [here](https://github.com/compucorp/civihr-employee-portal-theme/pull/256)) that they get assigned by default
I noticed that a lot of menu items were not included in the feature still, so I've added them
=> PCHR-2633: Export menu items with fa icons

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
This PR amends the "CiviHR admin" menu item by changing the label and assigning an icon to it.
It also adds an icon to the "Home" menu item, and removes the "CiviHR SSP" one as it was just a clone of "Home"
_(Related PR: https://github.com/compucorp/civihr-employee-portal-theme/pull/258)_
=> PCHR-2634: Update CiviHR Admin menu link

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/src/Blocks/MyDetailsData.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_aggregated_address.inc, civihr_employee_portal/views/views_export/views_my_details_block.inc
The "My Details" block has a few different displays. We're using different ones on the `/hr-details` page and `/dashboard`. These will be unified and old displays removed.
- `/hr-details` used a different display for the "My Details" view than on `/dashboard`.
- The master display for this view did not show Contact ID and Birth Date
- The address in the "My Address View" showed each address field separately
- The "My Details" view had 4 displays
- `/hr-details` uses the same "My Details" (master) display as on `/dashboard`.
- The master display for this view adds Contact ID and Birth Date
- The address in the "Contact Information (renamed)" is aggregated to a single field
- 2 obsolete displays are removed from "My Details" 
Previously we were adding all the address fields to the view, …
=> PCHR-2848: Updates to "My Details" Block

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/views/civihr_employee_portal.views.inc
Emergency Contacts are not currently selectable as a base entity for Drupal views to display. future tickets they are required so will need to be exposed to views.
The dropdown on the create view page did not show emergency contacts
The dropdown shows emergency contacts
Two things were preventing emergency contacts from being displayed:
- Only entities with base table info will be shown. This was not added by the CiviCRM module
- Attempts to add this data were overwritten by the CiviCRM module as the `views_data_alter` hook was called _after_ civihr_employee_portal
- The lines I uncommented were originally commented as part of [PCHR-539](https://compucorp.atlassian.net/browse/PCHR-539). I tested adding a leave to a staff member and could see it in the calendar both from admin and staff …
=> PCHR-2855: Expose Emergency Contact to Views

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/tasks.js, civihr_employee_portal/views/views_export/views_documents.inc, civihr_employee_portal/views/views_export/views_tasks.inc
This PR swaps every occurrence of the work "Assignment" with the word "Workflow" in the SSP, like it was done [here](https://github.com/compucorp/civihr-tasks-assignments/pull/276) in the T&A extension
=> PCHR-2869: Swap assignment with workflow in SSP

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/node_export_files/my_details.export, civihr_employee_portal/src/Forms/ContactForm.php
Keeping the Drupal user image in sync with the CiviCRM contact image is a pain. To lessen that pain we will remove the Drupal image from the Drupal user edit page and rely only on the CiviCRM contact image.
- The Drupal user edit page had an option to upload an image, which would not be reflected in CiviCRM.
- The maximum upload size for the user image in the "Edit My Details" webform was 2MB.
- When you updated a contact image on the CiviCRM profile page it was not reflected in the SSP dashboard
- The Drupal user edit page does not have an option to upload an image (achieved with drush command `drush vset --format=integer user_pictures 0`)
- The maximum upload size for the user image in the "Edit My Details" webform is 10MB.
- When you updated a contact image on the CiviCRM profile page …
=> PCHR-2783: Keeping Images in Sync

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/src/Forms/OnboardingWebForm.php
Existing CiviHR users might be a bit confused when required to complete onboarding. To help this we will add a message showing them why they're seeing it.
Anyone who hadn't completed onboarding would be redirected to the onboarding form without explanation.
There will be an explanation message on the first page of the onboarding form _only_ if the user was created before the onboarding form release date.
- Because the logic for form alterations was becoming more complicated I moved it into the form class itself.
---
=> PCHR-2864: Add Explanation for Onboarding Wizard for Existing Users

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/src/Blocks/MyDetailsData.php, civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_emergency_contact_aggregated_address.inc, civihr_employee_portal/views/views_export/emergency_contacts.inc, civihr_employee_portal/views/views_export/views_emergency_contacts.inc
To display the emergency contacts and dependants to the user we need to create a view with two displays.
There was no view for emergency contacts. The `/hr-details` page did not show emergency contacts or dependants.
The `/hr-details` page shows both emergency contacts and dependants.
---
=> PCHR 2849: Emergency Contact Views

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc
Since Leave can now be requested in Hours, a new field is needed on the SSP Leave and Absence Report as well as on the Pivot table that works the same way the Absence Duration in days field work.
The Absence duration in hours field does not exist.
- The Absence duration in hours field is added to the Leave and Absence report. 
The field is empty for absences in days. Also the Absence Duration in days field is empty for absences in hours.
---
This PR does not affect tests.
=> PCHR-2862: Add the Absence Duration in Hours field to the SSP Leave and Absence Report.

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/src/Blocks/MyDetailsData.php, civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php, civihr_employee_portal/views/includes/civihr_employee_portal_handler_emergency_contact_aggregated_address.inc
This PR combines a few minor planned fixes with some fixes that were discovered during the course of development.
- "Edit Emergency Contact" button appeared on /dashboard and /hr-details
- "Edit emergency contact" webform was still available
- "Emergency contact" and "dependants" displays were appearing in all "my details" blocks, not just on `/hr-details` as expected
- The emergency contact address order did not match the contact address order from `/dashboard`
- "Edit Emergency Contact" button does not appear on /dashboard and /hr-details
- "Edit emergency contact" webform is deleted
- "Emergency contact" and "dependants" displays appear under the "my details" block on `/hr-details` only
- The emergency contact address order now matches the contact address order from `/dashboard`
---
=> PCHR-2852: Minor Fixes

civihr_employee_portal/civihr_employee_portal.module
The assets of the `org.civicrm.shoreditch` extensions were leaking into the SSP, causing visual issues and also adding resources that the browser had to fetch for no reason
You can see the shoreditch style affecting the style of the SSP in the admin toolbar and in the header, for example
Network tab:
Now the SSP style is not affected, because the shoreditch style is not included in the ssp anymore
Network tab:
The entire `civihr_employee_portal.module` was fixed style-wise. This includes:
* Indentation
* Following proper phpdoc style for function documentations
* Using `[]` instead of `array()`
There were more fixes that could have been done (for example grouping related functions together), but at least it's a start
As part of [this …
=> PCHR-2949: Avoid injection of Shoreditch assets in SSP

civihr_employee_portal/civihr_employee_portal.module
When submitting a webform via AJAX (using a modal popup) the results will not be updated on the main page. Until now this was handled by redirecting the user to a page, however the redirect location was hardcoded to `/dashboard` which causes problems when submitting any webform from a different page.
Submitting any webform from any page using a modal would redirect to `/dashboard`.
Submitting any webform from any page using a modal will refresh the current page.
This callback is applied to any client webforms and only to the `#ajax` element of the form. Currently we have only the "Edit my Details" and "Create Emergency Contact" webforms, but the latter will be replaced the forms in PCHR-2846. We will also have the onboarding form, but that is not submitted using AJAX.
I cannot think of …
=> PCHR-2953: Fix Redirection from AJAX Webform Submissions

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/templates/civihr-employee-portal-my-details--block.tpl.php
This PR styles the newly created Emergency and Dependents blocks and their modal popup in HR Details Tab.. Refer https://github.com/compucorp/civihr-employee-portal-theme/pull/278 for screenshots.
**BackEnd**
1. Instead of relying on a drupal variable to store the ID of each webform we use the form title to decide if custom classes should be applied
1. The webforms created in the parent ticket were added to the list
**FrontEnd**
1. Added `visible-md visible-lg` instead of `hidden-xs hidden-sm` to the `vertical-splitter`, so that the line is not visible is iPad
---
=> PCHR-2947: Style HR Details

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
_(nevermind the name of the branch with the wrong ticket number, the correct ticket was created after the PR)_
Now with the [roles_for_menu](https://www.drupal.org/project/roles_for_menu) module added to the ssp (see https://github.com/civicrm/civicrm-buildkit/pull/379/files), the visibility setting of the help menu can simply be exported in a feature
=> PCHR-2961: Show help menu to auth users only, via upgrader

civihr_employee_portal/src/View/AbstractView.php, civihr_employee_portal/src/View/MyDetailsView.php, civihr_employee_portal/src/View/StaffDirectoryView.php, civihr_employee_portal/tests/HelperFunctionsTest.php, civihr_employee_portal/tests/View/AbstractViewTest.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/views_export/views_my_details_block.inc
The "my details" block uses filters for job contract and revision. These filters are problematic because if they don't match then nothing will be shown in the view at all.
The "my details" block used contextual filters for job contract and revision. Users without contracts only in the past or future would see no data at all on the "My Details" block on `/dashboard`.
The contextual filters are gone, and the "My Details" block on `/dashboard` will always show basic info, as well as contract and role data for the current contract _if_ it is available.
I also moved some code out of the module file into a separate class to represent each view we have. This should help keep the module file smaller and improve encapsulation.
This uses the `hook_views_query_alter` hook to change the query. By …
=> PCHR-2927: My Details Contract Filter Fix

civihr_employee_portal/civihr_employee_portal.install
Onboarding form export and import uses `location_type_id`. However `location_type_id` can be different from site to site. This PR sets the onboarding form fields to use the correct location types.
On staging some of the location type IDs were different and pointed to unexpected location types for onboarding form components.
The onboarding form components use the correct location type IDs.
- Work Phone Number (Work - Phone)
- Home Phone Number (Home - Phone)
- Work Email (Work)
- Home Email (Home)
- Instant Messenger (Work)
- This is a temporary fix. More comprehensive fixed to improve the importing and exporting of webforms will be done at a later stage.
---
=> PCHR-2988: Fix Onboarding Form Location Types

civihr_employee_portal/css/custom.css, civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php
This PR adds the following changes to the report tabs menu:
* Renames the tabs items.
* Adds icons to each item.
* Changes the order of the menu items.
* makes the first option's width 85% of the container.
The tabs were renamed as follows:
* Pivot Table ---> Report Builder
* Data ---> View Data
The order was changed so the Report Builder goes first and View Data second.
Tab items were changed from display like table-cell to display inline to be able to change the width of the Report Builder item:
```css
.report-tabs {
font-size: 0; /* Removes gap between inline-block elements */
margin-top: 12px;
}
.report-tabs.nav-tabs.nav-justified > li {
display: inline-block;
font-size: 0px;
min-width: 15%;
}
.report-tabs.nav-justified > li:first-child {
min-width: 85%;
}
```
Backstop scenario …
=> PCHR-3038: Report tabs menu changes

civihr_employee_portal/css/custom.css, civihr_employee_portal/js/reports.js, civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php
This PR updates the layout of the report page so it follows the mock detailed in the [Report Improvements Wiki](https://compucorp.atlassian.net/wiki/spaces/PCHR/pages/123699243/Reporting+User+Experience+Improvements).
To replace the layout DOM manipulation was needed since the report is generated by the [Pivot Table plugin](https://github.com/nicolaskruchten/pivottable) which doesn't support custom templates.
The template is first appended inside the pivot table container:
```js
HRReport.prototype.createReportSectionElement = function () {
var html = '<div class="report-section">' +
'<div class="row report-header-section">' +
'<div class="report-filters col-sm-3"></div>' +
'<div class="report-function col-sm-2">' +
'<div class="report-function-select"></div>' +
'<div …
```
=> PCHR-3040: Report layout update

civihr_employee_portal/css/custom.css, civihr_employee_portal/js/reports.js, civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php
This PR adds a few fixed requests in [this comment](https://github.com/compucorp/civihr-employee-portal/pull/414#issuecomment-355333041) including:
* The configuration options were aligned to the "report builder" title.
* The configurations list was expanded to 100% so it's aligned with the chart type select and its own save/delete options.
* The configuration options (save, update, and delete buttons) are displayed depending on the context. If there are no configurations saved only "Save as New" is displayed.
In addition this PR fixes these two issues:
* The report would still be visible when switching to the "View Data" tab.
* Field instructions would still be visible when switching report configurations.
Only "Save as New" is displayed when there are no configurations saved. …
=> PCHR-3133: Report configuration changes

civihr_employee_portal/civihr_employee_portal.module
Although tests in CiviHR Employee Portal are running, tests in Tasks and Assignments are not because TASettings are fetched in an `init` function of this module.
T&A tests would not run because of an error related to fetching TASettings.
TASettings are only fetched if T&A is enabled. Tests in T&A can run.
The tests in T&A were failing because `civihr_employee_portal_init` was being called when the T&A extension was not enabled. `civihr_employee_portal_init` calls `_load_ta_settings`, which does an API request to fetch `TASettings`. The `TASettings` API is provided by T&A so this call failed.
---
=> PCHR-3053: Fix T&A Tests

civihr_employee_portal/css/custom.css
This PR fixes an issue where the dropdown arrow of select elements inside of the report page would not open their select element when clicked.
Clicking on the dropdown arrow doesn't work.
This issue was introduced by [this commit](https://github.com/compucorp/civihr-employee-portal/commit/ab00dce2) since it overrides the z-index of the select element which originally was 2. The purpose of this commit was to fix date pickers to display above the select elements.
The datepickers were not being displayed on top of the selects because a parent element was using `z-index: 1` ([here](https://github.com/compucorp/civihr-employee-portal/pull/418/files#diff-c9717edfd0ee9646951283cf7eadc4e4L205)).
These z-index rules were not needed and were introduced in order to fix z-index issues before the …
=> PCHR-3177: Fix Report dropdown arrows

civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php
This PR removes the Report Builder header from report pages. 
The reason to remove this header is because it's part of the [Report Improvement requirements](https://compucorp.atlassian.net/wiki/spaces/PCHR/pages/123699243/Reporting+User+Experience+Improvements).
This markup was removed from `civihr-employee-portal-civihr-report-custom.tpl.php`:
```html
<div class="chr_search-result__header">
<div class="chr_search-result__total">
Report Builder
</div>
</div>
```
=> PCHR-3178: Remove "Report Builder" header

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/features/node_export_files/onboarding_form.export
The onboarding form user image upload size limit should be 10 MB. It is currently 2 MB
The onboarding form user image upload size limit was 2 MB
The onboarding form user image upload size limit is 10 MB
---
=> PCHR-3012: Onboarding Form Image Upload Limit

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/reports.js, civihr_employee_portal/templates/civihr-employee-portal-civihr-report-custom.tpl.php
This PR renames the labels for the report filters based on these mockups:
Leave and Absence report filters:
People's report filters:
Leave and Absence's report:
People's report:
Leave and Absence's report:
People's report:
The `civihr_employee_portal_form_views_exposed_form_alter` method was refactored. This method now redirects the flow to the specific form alteration functions depending on the form ID:
```php
function civihr_employee_portal_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
switch ($form['#id']) {
// People's report filters:
case 'views-exposed-form-civihr-report-people-default':
_civihr_employee_portal_form_view_exposed_form_alter_people_report($form, $form_state, $form_id);
break;
// Leave and Absence's report filters:
case …
```
=> PCHR-3175: Rename filter labels

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/js/reports.js
This PR updates the default report filter dates depending on the report:
* For People's report the default date is the current date.
* For Leave and Absence's report the default dates are the current absence period start and end dates.
<table>
<tr>
<th>People's report</th>
<th>Leave and Absence</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/1642119/35097108-205f5e94-fc25-11e7-9d54-e409889be1d9.png" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/35097163-6997b250-fc25-11e7-87c9-da0950f25776.png" /></td>
</tr>
</table>
<table>
<tr>
<th>People's report</th>
<th>Leave and Absence</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/1642119/35096875-2e3d3190-fc24-11e7-85ef-aa4797730550.png" /></td>
<td><img …
=> PCHR-3176: Default filter dates

civihr_employee_portal/css/custom.css, civihr_employee_portal/js/reports.js
This PR fixes the following report page issues:
* SVG charts breaking the new report layout. 
* Make the report look better in small screens, though it doesn't rearrange the elements as there are no wireframes for it.
* Fixes an issue where the data table scrolls would not appear  until scrolling with the mouse wheel or by chance.
**Note:** Fields selection can't have a `overflow: scroll` without considerable JS changes since the draggable elements don't work well with overflowed elements.
**Notes:** The scrollbar only appears after scrolling with the mouse wheel. This is not a regression issue, it has been like that since the implementation of the report.
Some of the CSS rules for the pivot table where moved from the static [civihr_employee_portal/css/custom.css](https://github.com/compuc …
=> PCHR-3207: SSP Report fixes

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/css/reports.css
This PR was created to support the work done on https://github.com/compucorp/civihr-employee-portal-theme/pull/304. It includes the CSS to hide the Admin toolbar. Please check the linked PR for more details
=> PCHR-3210: Hide the admin toolbar in the SSP reports pages

civihr_employee_portal/views/templates/views-view-table--Tasks--block.tpl.php
This PR adds a helper class `create-new-task` for the backstop js tests in https://github.com/civicrm/civihr/pull/2426
=> PCHR-3202: Add helper class for backstop

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/src/Forms/OnboardingWebForm.php, civihr_employee_portal/src/Helpers/LinkProvider.php
Based on client feedback some people felt that there should be an option to skip the onboarding form. We [previously](https://github.com/compucorp/civihr-employee-portal/pull/387) added a description for users who had been created before the onboarding release. This description will be extended to all users, but the content will depend on whether they are users created before the onboarding release.
- There was no button to skip the onboarding form
- Only users created before the onboarding form release were shown a message explaining the form
- There is a button to skip the onboarding form
- All users will have a description of the onboarding form
- The description will differ depending on whether they were created before the onboarding form release
- The link will bring users with …
=> PCHR-3209: Add Link to Skip Onboarding

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.features.menu_links.inc
This PR renames the "HR admin" link on the SSP menu to "HR Admin" (capital A).
The HR Admin menu link was updated using the Admin Structure interface. Only the changes related to the link renaming were committed since there is another [issue with the Report Settings block](https://compucorp.atlassian.net/browse/PCHR-3223?focusedCommentId=65854&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-65854) that needs to be addressed separately.
=> PCHR-3223: Rename HR Admin link

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/civihr_employee_portal.module
This PR adds a default set of configuration for the SSP reports. 
New and existing sites didn't have any default report configuration
There are 16 default configurations. 12 of them are for the People report, and the remaining ones are for the Leave report. New and existing sites will have all of them.
For the People report, the new configurations are:
- Age Group by Department
- Age Group by Location
- Average Pay Amount by Contract type and Department
- Current Headcount by Location and Department
- End of Contract till Date Report
- Full-time Equivalence by Contract type and Location
- Full-time Equivalence by Location and Department
- Gender by Department
- Gender by Level
- Gender by Location
- Headcount by Contract Type
- Pay Parity by Gender and Contract Type
For the Leave report, …
=> PCHR-3227: Creates default reports configuration

civihr_employee_portal/views/views_export/views_tasks.inc
In SSP Tasks page, Show completed tasks popup does not show any notification when there are no completed tasks. This PR fixes the bug.
Added `NO RESULTS BEHAVIOR` to the `Completed Tasks block` in drupal.
=> PCHR-3203: Tasks page modal No Result behaviour fix

civihr_employee_portal/templates/smarty/user_account_activated.tpl, civihr_employee_portal/templates/smarty/user_password_reset.tpl
When sending the password reset email, or the user account creation email for the first time, a large number of warnings will appear mentioning unknown tags in the smarty templates. 
The first time the user account creation email, or the password reset email was sent it would generate a lot of warnings. The mail was still sent, and because templates are cached the warnings would not appear again. After clearing the `civicrm` cache the warnings would return another (single) time.
Even with a clean cache no warnings are produced when sending the user account creation or password reset emails.
The warnings are generated because smarty tries to interpret the `<style>` element and finds curly braces. Smarty uses curly braces to designate a block that it should parse, similar to how PHP will …
=> PCHR-3090: Fix Smarty Warnings

package-lock.json, package.json
See https://github.com/civicrm/civihr/pull/2473
This repo does not have SASS files, only plain CSS files. For this reason [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) had been used instead of [stylelint-config-sass-guidelines](https://github.com/bjankord/stylelint-config-sass-guidelines)
=> PCHR-3246: Implement stylelint for CSS files

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/templates/civihr-employee-portal-civihr-report-landing-page.tpl.php
On https://github.com/compucorp/civihr-employee-portal/pull/434, we made the SSP reports accessible in the CiviHR admin, using iframes. 
On the SSP, the report pages were updated to render without any surrounding elements (headers, footers, etc), so that, when displayed inside an iframe, they would look like as being part of the page. However, it's possible that some users have bookmarked these pages and, if they try to access them, they will see only the iframe contents. To fix this, we will now redirect any direct access to the reports in the SSP to the respective URLs in the CiviHR admin.
Users could access the report pages directly from the SSP. This would result in them seeing an almost empty page, without headers and footers.
If users try to access the report pages directly from the …
=> PCHR-3285: Redirect from the SSP report pages to the CiviHR admin

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/src/Forms/OnboardingWebForm.php, civihr_employee_portal/src/Helpers/UrlHelper.php, civihr_employee_portal/tests/Helpers/UrlHelperTest.php
During the course of onboarding testing we discovered that when using the image uploaded from the webform for a contact image CiviCRM would show a warning about [an undefined "photo" index.](https://github.com/civicrm/civicrm-core/blob/17ae6ca46f1d544d40e5bfb77ab6727975ba7e17/CRM/Utils/File.php#L913).
To fix this I made [this commit](https://github.com/compucorp/civihr-employee-portal/pull/406/commits/92cc1dffd0f20040f1a58c2cf8ded77896eafbe1) to add `photo=0` to images when the onboarding form was submitted. This fixed the warning and both regular images and images saved from the webform were displayed without warning.
Unfortunately I did not consider this case:
1. A contact was created and somebody uploaded an image for them
1. This contact logs in and goes through the onboarding form
1. …
=> PCHR-3269: Fix Image Query Params

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.info, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/views/views_export/views_users_list.php
This PR creates a users list view that is similar to the default Drupal view found at `/admin/people` but it is a more stripped down version. 
The users list view excludes users with the Drupal Administrator role and has bulk operation functionality to modify the roles of a user and also to block a user role.
The users list view does not exist.
The users list view was created and is accessible at the URL: `/users-list` and users with the `administer users` permissions can view the page.
- The bulk operations functionality is provided by the already installed Views Bulk Operations module. 
- The unblock user functionality is not available by default with Views Bulk operations module see [here](https://www.drupal.org/project/views_bulk_operations/issues/1293600) except by using a workaround …
=> PCHR-3311: Create Users List view.

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/views/civihr_employee_portal.views.inc
The CiviHR installation (both with buildkit or with the ansible playbook) is failing with this error:
```
>> Unable to patch views_json_query with views_json_query_civihr-v1.patch.    [error]
```
This PR removes the `views_json_query` module dependency to fix the error.
The CiviHR installation would fail at the step where a [patch](https://raw.githubusercontent.com/compucorp/civihr-employee-portal/master/patches/views_json_query_civihr-v1.patch) is applied to the views_json_query module. We use[ a development version](https://github.com/civicrm/civicrm-buildkit/blob/6aa2f04d131e3e1c6f7f3c5d5dfd1af779c31829/app/config/hr17/drush.make.tmpl#L205) of that module and that version was updated on earlier this month, as it's possible to see here:
The patch is not compatible with this version, …
=> PCHR-3283: Remove the views_json_query dependency from the SSP

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/templates/views-view-table-scrollable-with-results.tpl.php, civihr_employee_portal/templates/views-view-table.tpl.php, civihr_employee_portal/views/templates/views-view--users-list--page.tpl.php, civihr_employee_portal/views/views_export/views_users_list.php
As part of this PR the User List page in SSP is styled.
Refer https://github.com/compucorp/civihr-employee-portal-theme/pull/319
1. `_civihr_employee_portal_form_view_exposed_alter_users_list ` has been added to `civihr_employee_portal.module`. Which applies `col-sm-6` class and also changes the labels for the Access field.
2. `views-view-table-scrollable-with-results.tpl.php` is created to show view tables with scrolling and also with results information on the header.
=> PCHR-3342: Style Users List

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
Sequel to [#2493](https://github.com/civicrm/civihr/pull/2493), which adds a new Permission: `CiviHRContactActions: Administer Staff Accounts` which will be used to access the User related links on the Contact actions menu  and also the new Users List page in SSP.  The `administer users` and `access users overview` permissions were revoked from the HR Admin and Regional HR Admin roles (since we no longer want these roles to have access to `admin/people` anymore) and the permission:  `administer staff accounts` was assigned to these roles.
The Manage Users Link in the SSP will be changed to point to the new Users List view and the permission updated in another PR.
- The HR Admin and Regional HR Admin have access to the `administer users` and `access users overview` permissions.
-  The HR …
=> PCHR-3346: Revoke permissions and assign new permission for to relevant roles

civihr_employee_portal/civihr_employee_portal.module
This PR renames the default option for the Bulk operations dropdown from `Choose an operation` to `Bulk edit`
The default option for the Bulk operations dropdown is `Choose an operation`
The default option for the Bulk operations dropdown is `Bulk edit`
Changes does not affect tests.
- [] Tests Pass
=> PCHR-3362: Rename Default option to bulk edit.

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/templates/views-view-table-scrollable-with-results.tpl.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
In SSP Staff Directory, the views table was broken in the mobile view. This PR fixes that.
1. In `civihr_employee_portal/civihr_employee_portal.module`
Added `civihr_staff_directory` to the `$viewsList` array in `_is_scrollable_table_view_with_results` function, to use the `views-view-table-scrollable-with-results.tpl.php` which is meant to solve the scroll issue.
2. In `civihr_employee_portal.views.inc`
Removed `($view->name == 'civihr_staff_directory' && $display_id == 'page')` condition as `views-view-table-scrollable-with-results.tpl.php` already holds the header count.
3. From the staff directory view, removed the header from drupal views menu as `views-view-table-scrollable-with-results.tpl.php` already holds the header count.
4. In `views-view-table-scrollable-with-results.tpl.php` …
=> PCHR-3273: Fix Staff Directory Responsiveness

civihr_employee_portal/views/includes/civihr_employee_portal_handler_aggregated_address.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_emergency_contact_aggregated_address.inc
Please check https://github.com/civicrm/civihr/pull/2545 for more details.
This is basically the same fix, but to some Drupal code, that was using the API and/or BAOs to fetch data from CiviCRM and print it to the screen. Here, the `filter_xss` function from the Drupal API was used to filter the data.
=> PCHR-3487: Escape user entered data

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc, civihr_employee_portal/views/views_export/views_civihr_report_people.inc
When the Leave Report and People Report on the SSP are exported on a Windows machine, the exported format is not in CSV and as such can not be readily opened. This PR fixes the issue.
When the Leave Reports and People Reports on the SSP are exported on a Windows machine, the exported format is not in CSV and as such can not be readily opened.
- Ticking the Provide as File option in the Data Export settings for the respective view fixes this issue. In order for this fix to be applied for all affected sites, the Views and Features for the Leave report and People report were re-exported after ticking this option via the UI.
=> PCHR-3254: Fix Reports Export Not Being in CSV Format on Windows

civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
We need to hide the Contract type column on the SSP staff directory view.
- The Contract type column shows on the  SSP staff directory view
=> PCHR-3496: Hide Contract Type column from the SSP staff directory View

civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/views_export/views_hr_staff_directory.inc
Contacts with only a single inactive role or only a single inactive relationship were not displayed in the staff directory view
- Contacts with only inactive roles did not show in the staff directory view
- Contacts with only inactive relationships did not show in the staff directory view
- All contacts with active contracts are shown regardless of role or relationship status
The issue with filtering by role end was originally dealt with in PCHR-1890 by [removing](https://github.com/compucorp/civihr-employee-portal/commit/cd15baf1ed35d1530e08f65baf3b64bdd95acb54) the filter.
[This commit re-added a role filter](https://github.com/compucorp/civihr-employee-portal/commit/7f1b3d142c731198943e4c285db02ee3ad2e0150) and [this commit added a relationship …
=> PCHR-3573: Fix Staff Directory View (round 2)

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/templates/civihr-employee-portal-user-login.tpl.php
When redirecting a user to the login form the fragment part of the URL was lost, this meant that someone coming to `mysite.civihr.org/reports#my-report` would be redirected to `mysite.civihr.org/reports`.
The fragment was not included in the URL when redirecting
The fragment is included in the URL when redirecting
We're accessing the fragment _after_ being redirected to the login page. This relies on the fragment being retained after a redirect. According to an answer on [Stack overflow](https://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects)
> IE10+, Chrome 11+, Firefox 4+, and Opera will all "reattach" the original URI's fragment after following a 3xx redirection.
Which meet the minimum requirements for CiviHR. This means the process will be
1. Try to access …
=> PCHR-3627: Include URL fragment in redirection

civihr_employee_portal/features/civihr_default_mail_content/civihr_default_mail_content.strongarm.inc
After originally merging #467 some additional changes were requests
- The user guide link pointed to https://civihr-documentation.readthedocs.io/en/latest/initial-setup-and-configuration/staff-managers-quickstart/
- The user guide link points to http://userguide.civihr.org
- A sentence was removed
---
=> PCHR-3569: Update user guide link. Remove sentence.

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc, civihr_employee_portal/js/reports.js, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/views_between_operation_dates_filter_handler.inc, civihr_employee_portal/views/views_export/views_civihr_report_leave_and_absence.inc
Recently, We have been having some performance issues with the Leave and Absence Reports on sites with particularly large leave data. On closer investigation, it was discovered that the Leave filters for this report does not work and it fetches the data set all at once and does not allow to fetch the data in chunks. 
The date filter for the people report works but the whole data is fetched on initial page load.
- The date filters on the Leave and Absence report does not work.
- The date filter for the people report works but the whole data is fetched on initial page load.
- The date filters on the Leave and Absence reports was fixed and also on first load, the pivot table fetches result for the current year so as not to fetch the result set at once. The whole result set can still be …
=> FAR-265: Fix Date Filter Issue On Leave Reports and People Reports

civihr_employee_portal/civihr_employee_portal.install, civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
We want to remove usages of the "Home", "Main" and "Other" location types as they will be deleted by an upgrader in CiviHR. These location types are in use in this repo and should be replaced or removed.
- An upgrader existed to fix location type IDs in the onboarding form
- The `hrjc_contact_details` view used the "Home" location type for email and phone 
- The upgrader is not required and has been removed
- The `hrjc_contact_details` view uses the "Personal" location type for email and phone
---
=> PCHR-3730: Replace "Home" location type with "Personal"

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/features/node_export_files/onboarding_form.export
The onboarding form used the "Home" location type for phone, email and address. This PR changes that to "Personal" location type
The onboarding form phone, email and address inputs referenced the "Home" location type
The onboarding form phone, email and address inputs reference the "Personal" location type
---
=> PCHR-3537: Change "Home" location type on onboarding form to "Personal"

civihr_employee_portal/civihr_employee_portal.module
As part of this PR Relations, Description and Text Format has been hidden from document types add/edit screen.
=> PCHR-3705: Hide Relations and Description from HR Resource type adds screen

civihr_employee_portal/js/reports.js
The current default date filter values for the Leave and Absence reports is for the current year, However some sites with large data still find it difficult to load this data at once, so this PR changes the default filter values and data fetch to be for the current month.
- The date filter for the leave and absence report is defaulted to current year and data is fetched for current year as well.
- The date filter for the leave and absence report is now defaulted to current month and data is fetched for current month as well.
Changes does not affect tests.
=> PCHR-3792: Set Leave And Absence Report filter to Current Month

civihr_employee_portal/civihr_employee_portal.module
Currently, deleted leave requests show up on the Leave and Absence Reports. This PR fixes the issue by ensuring deleted leave requests does not show up on the reports.
- Deleted leave requests show up on the Leave and Absence Reports
- Deleted leave requests does not show up on the leave and Absence Reports
Changes does not affect tests.
=> PCHR-3804: Exclude Deleted Leave Requests From Leave Report.

civihr_hrjobcontract_entities/civihr_hrjobcontract_entities.module
Currently when a the contract details for a contact is edited and saved and a new contract revision is created, this leads to duplicate data for that contact in Leave reports and the leave count for the contact also increases and becomes inaccurate. Basically as more revisions are made, the data becomes more duplicated.
- The `hrjc_revision` VIEW is part of the table the Leave and Absence reports pull data from, It contains all the current and past revisions for a contract. In reality what we actually need is the latest revision for the contract.
- The query for generating the `hrjc_revision` VIEW is modified to create the view to contain only the latest revision for a contract.
changes does not affect tests.
=> PCHR-3802: Fix Duplicate Data Issue in Leave Reports When After Saving A New Job Contract Revision

civihr_employee_portal/civihr_employee_portal.install
During a merge conflict one of the upgraders was dropped which meant the node export files were not re-imported
There was no upgrader to migrate changes from staging to the location types changes
An ugprader has been added to refresh the nodes and apply changes from the location types feature
---
=> PCHR-3537: Re-add missing upgrader

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
The following bugs related to the Manage Resource Page has been fixed
1. The Custom Publish checkbox's value should be saved only when its visible.
2. The Title in the Manage Resource page should link to the edit page of the node.
1. `isPublishStatusCheckBoxVisible()` function has been created, and the logic to show the checkbox is moved here. The same is used in `civihr_employee_portal_node_presave()` and in `civihr_employee_portal_form_alter`.
=> PCHR-3835: Manage Resources Page elated bug fixes

civihr_employee_portal/civihr_employee_portal.module
The ssp module will now populate Google Analytic's `dataLayer` with the user's roles (minus the "authenticated user", which is a given).
The user roles, stored in the `userRoles` property, will be then used as custom dimension to create GA reports
=> PCHR-3861: Fill data layer container on module init

civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.views_default.inc
When HR Resources are edited using the title link, and saved, page should be redirected to the Manage HR Resources Page. This PR fixes that bug.
This ticket is a subtask of PCHR-3674, so ideally I should be creating a PR to 3674 branch, and once merged, create another PR to staging. But as PCHR-3674 already got merged and then this ticket got reopened, I am creating PR directly to staging.
=> PCHR-3835: Fix url for title in Manage HR Resources Page

civihr_employee_portal/civihr_leave_absences/civihr_leave_absences.module
Currently the Leave and Absences permissions are added to the `CRM.permissions` global variable
for SSP only. For the Calendar Epic, some tasks require checking user permissions in the civicrm Admin pages, this PR adds the  Leave and Absences permissions to the  `CRM.permissions` global variable also for Civicrm pages.
- The Leave and Absences permissions are added to the `CRM.permissions` global variable
for SSP (non civicrm pages) only
- The Leave and Absences permissions are added to the `CRM.permissions` global variable
for both civicrm and non civicrm pages.
Changes does not affect tests.
=> PCHR-3920: Populate the CRM.permissions Global Variable with Leave and Absence Permissions for Civicrm pages.

civihr_employee_portal/civihr_employee_portal.module
The SSP module tried to use the `datalayer_add` regardless of the presence and/or status of the "datalayer" module, resulting in the SSP breaking if the module was disabled or non existing
The PR simply adds a check to determine if the "datalayer" module exists, before using its function
=> PCHR-3925: Check if datalayer module exists before using it

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
When logged in as Regional Admin, SSP theme is not applied for the following pages
1. Create HR Document (Manage HR Resources -> Add HR Resource) - /node/add/hr-documents
2. Edit HR Document(Manage HR Resources -> Edit a Document)
3. Delete HR Document(Manage HR Resources -> Edit a Document)
4. Add HR Resource Type(HR Resource Types -> Add HR Resource Type)
5. Edit HR Resource Type(HR Resource Types -> Edit an existing HR Resource Type)
Removed `view the administration theme` permission for `regional_admin`.
=> PCHR-3907: Show SSP theme for Regional Admin

civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc
In `/node/add/hr-documents` page, the Revision section is visible for Regional HR Admin. But it should not. This PR fixes that bug.
The permissions of **Regional HR Admin** and **HR Admin** were not same and hence this bug. Both the roles should have the exact same permissions. So changed all permissions of Regional HR Admin to exactly mimic HR Admin.
**For Devs:**  To test this, open permissions page in drupal, HR Admin and Regional HR Admin should have the same permissions.
=> PCHR-3932: Fix Regional HR Admin Permissions

civihr_employee_portal/src/Security/PublicFirewall.php, civihr_employee_portal/tests/Security/PublicFirewallTest.php
This PR adds the leave calendar feed generation URL to the `PublicFirewall` class so that it can be publicly accessible.
The `civicrm/calendar-feed` URL was not publicly accessible.
- The `civicrm/calendar-feed` URL is now publicly accessible.
=> PCHR-3870: Make Calendar Feed Generation URL Public

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/features/node_export_files/onboarding_form.export
Currently the `Payroll` section of `Onboarding Wizard` provides two options - 
* Add Now
* Add Later
This PR renames the `Add Later` option to `Skip this step`
The display text of the option group was changed
=> PCHR-3950: Onbarding Wizard - Change Option Add Later to Skip this Step

civihr_employee_portal/views/views_export/views_mydetails_myrole.inc
This PR fixes the styles for Job Roles section of My Details page.
1. If a class with underscore's are specified in drupal, it gets converted to dash. So moved the class `chr_panel--my-details__view__panel` to the template.
=> PCHR-3965: Job Roles Layout fixes

civihr_employee_portal/features/node_export_files/mydetails_home_address.export
In Home Address webform from My Details page Postal code is showing above city. It should be the opposite, City must be above Postal Code.
=> PCHR-3969: Move City Above Postal Code in My Home Address Webform

civihr_employee_portal/civihr_employee_portal.module
As part of this PR the path for `reqangular.min.js` is updated for the Reports page.
In PCHR-3942 (https://github.com/compucorp/civihr/pull/2772) the path for `reqangular.min.js` was changed, but the same was not updated in `civihr_employee_portal.module`, which broke the Reports pages.
The path has been fixed.
---
=> PCHR-4010: Update path for reqangular.min.js

civihr_employee_portal/civihr_employee_portal.module
This PR removes the inclusion of Bootstrapcivihr CSS resource files from all SSP pages. This PR is tightly related with https://github.com/compucorp/civihr-employee-portal-theme/pull/377.
Every SSP page source HTML contains:
```html
<link type="text/css" rel="stylesheet" href="http://localhost:8888/sites/all/modules/civicrm/tools/extensions/civihr/org.civicrm.bootstrapcivihr/css/civihr.css?r=7B2iE" media="all" />
```
None of SSP pages source HTML contain the CSS file inclusion link mentioned in the Before section.
Same method as seen at https://github.com/compucorp/civihr/pull/2166/files#diff-121b31ed9140681ebf2bf197b1aa8821R124 is used. However, the resource removal function is now universal and accepts an `$extension` parameter:
```php
function _remove_extension_resources($extension, …
```
=> PCHR-3424: Remove Bootstrapcivihr theme inclusion from SSP

civihr_employee_portal/civihr_employee_portal.module
In https://github.com/compucorp/civihr/pull/2775, the `require.min.js` has been detached from `reqangular.min.js`. In this PR the 'require.min.js' is attached to the DOM
=> PCHR-3941: Detach require.min.js from reqangular

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/src/View/CustomFieldsMappingFixer.php
Depending on the creation of CiviCRM custom fields and CiviCRM custom tables their names may vary on different installations. Examples:
- From `custom_field_25` to `custom_field_10001`
- From `custom_table_38` (exported table name from another site) to `custom_table_51` (existing table on current site)
When these fields/tables names change it may produce bad references when importing views that use these names, which generates empty queries due to missing fields or tables, which in turn causes views not showing the expected results.
It happens when a Custom Group/Field is created using the CiviCRM API. The table and field names will get the next ID available at the moment the API call is made and there's no way to guarantee that this next ID will be the same in all sites. This is why …
=> PCHR-4037: fix views import of custom fields at the creation of views

civihr_employee_portal/src/View/StaffDirectoryView.php
Filtering staff records in SSP have some issue with job roles that are not active. This PR fixes the issue by applying additional filter condition to job role start date. Date filtering is now applied to filter requests containing department and job title.
Staff with job roles starting in the future or past end dates show up when running filter.
Staff with job roles starting in the future or past end dates no longer show up in filter result.
In [Staff Details View](https://github.com/compucorp/civihr-employee-portal/blob/staging/civihr_employee_portal/src/View/StaffDirectoryView.php#L15) the query was altered to cater for `job title` and `role start date` field in addition to `department` and `role end date` fields.
```
$titleField = 'hrjc_role_hrjc_revision.role_title';
$roleStartField = …
```
=> PCHR-4073: Fix SSP Filter on Staff Directory

civihr_employee_portal/src/Forms/OnboardingWebForm.php
Previously, onboarding wizard shows two different message based on when site was created (before or after onboarding feature). This PR unifies the intro text for all users. 
Conditional checks were removed and single intro response returned for all setup.
```
...
return 'Please start by entering your details below.'
. '<br/><br/> You can always update these details later.';
...
```
=> PCHR-3952: Intro text for Onboarding Wizard

civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
Add settings to let HR Admin to configure notifications when a contact changes its details.
Settings added to the Onboarding Wizard config form.
=> PCHR-4034: Settings to Send Notifications on Contact Details Changes

civihr_employee_portal/civihr_employee_portal.module, civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php, civihr_employee_portal/src/Helpers/WebformHelper.php, civihr_employee_portal/src/Mail/AbstractDrupalSystemMail.php, civihr_employee_portal/src/Mail/MailContentReplacer.php, civihr_employee_portal/src/Mail/OnboardingFormEditNotificationMail.php, civihr_employee_portal/src/Mail/WebformSubmissionNotificationMail.php, civihr_employee_portal/src/Mail/WebformSubmissionNotifier.php, civihr_employee_portal/templates/smarty/dashboard_edit_details.tpl
The purpose of this PR is to send notification mails to a specific user when someone updates their information either via the webforms on the SSP dashboard or via the onboarding form.
When a user updated their info via the SSP or onboarding form no notifications were sent.
When a user updates their info via the SSP or onboarding form a notification is sent containing the submitted values to a specific email.
This PR builds on #528 which added the notification settings.
The flow for the notifications is:
- Inside `hook_webform_submission_insert` call `WebformSubmissionnotifier::sendNotification`
- `sendNotification` checks notification settings to decide whether the mail should be sent
- `WebformSubmissionnotifier` fetches the target email and calls `drupal_mail`
- …
=> PCHR-4155: Notification Mails for SSP Edit and Onboarding Form

civihr_employee_portal/src/Forms/OnboardingWizardCustomizationForm.php
This PR makes small amendments to the css classes of the "Send an email when someone updates their details" block, so that the code in https://github.com/compucorp/civihr-employee-portal-theme/pull/378 can style that block correctly
=> PCHR-4034: Additional fixes

civihr_employee_portal/src/View/CustomFieldsMappingFixer.php, civihr_employee_portal/views/views_export/views_my_details_block.inc
We want to show the NI/SSN and "Is applying for NI/SSN" fields in the "My Details" View
The fields were not present in the view
The NI/SSN and "Is applying for NI/SSN" fields are displayed in the view
Even without HTML tags in the view field the `<p>` tag was being added to the "NI/SSN" field so I added "strip HTML tags" and "remove whitespace" to this field
Since it is possible for the "Is applying field" to be empty I added a default to "No"
There were some formatting issues in the `CustomFieldsMappingFixer.php` file so I ran the PHPStorm code formatter and fixed any issue that `civilint` reported
---
=> PCHR-4030: Add Fields to "My Details" View

civihr_employee_portal/civihr_employee_portal.install
On https://github.com/compucorp/civihr-employee-portal/pull/532/, an upgrader was added to remove "Vancacies" from the SSP menu. Originally, this upgrader number was 7036. Before this was merged to `staging`, another PR (https://github.com/compucorp/civihr-employee-portal/pull/536) was merged adding an upgrader with the same number.
This caused a conflict which we tried to fix in https://github.com/compucorp/civihr-employee-portal/pull/532/commits/05cd2c696b25391ef9191e010feded7635d9def6. When fixing conflicts with upgrader coming from staging, the only correct approach is to change the upgrader in our PR to a number higher than whatever we have on staging. The reason is that, if we pick a lower number the upgrader will never be executed. Unfortunately, this is not what happened here. The …
=> PCHR-3930: Fix upgrader numbers

civihr_employee_portal/civihr_employee_portal.info, civihr_employee_portal/src/Service/CustomValueService.php, civihr_employee_portal/views/civihr_employee_portal.views.inc, civihr_employee_portal/views/includes/civihr_employee_portal_handler_ni_ssn_or_status.inc, civihr_employee_portal/views/views_export/views_mydetails_personal.inc
This PR adds the NI/SSN to the personal details section of the `/hr-details` page.
The NI/SSN field was not displayed on this page.
The field is displayed in the personal details section after the "Nationality" field
If the NI/SSN application is in progress the text _pending_ is displayed instead
If NI/SSN is not in progress but there is no NI/SSN number set the field will be hidden (as is default for views fields)
The decision to add a custom handler was because of the complexity of the logic in the requirements, i.e. we want to re-write the results based on a separate field. 
Another reason for using a custom handler was because views are susceptible to problems related to CustomGroup and CustomField IDs differences between systems. In the custom handler we use a new service which …
=> PCHR-4030: NI/SSN Fields on HR Details Page

civihr_employee_portal/civihr_employee_portal.install, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.features.user_permission.inc, civihr_employee_portal/features/civihr_default_permissions/civihr_default_permissions.info
When editing a user profile by `HR Admin`, option for assigning `Regional HR Admin` role to edited profile was not available. This PR fixes the issue by assigning required permission to `HR Admin` user.
Permission to `Assign Regional HR Admin role` was added granted `HR Admin`. This makes the option available to grant edited profile permission.
```
$permissions['assign Regional HR Admin role'] = array(
'name' => 'assign Regional HR Admin role',
'roles' => array(
'HR Admin' => 'HR Admin',
),
'module' => 'role_delegation',
);
```
---
=> PCHR-4173: Local Admin Role is not available

civihr_employee_portal/civihr_employee_portal.module
When creating new HR Resource in SSP, a PHP Notice is generated when form alter hook is running. This PR fixes the issue.
The Notice was due to the fact form node was not set. Attempting to read `nid` on a non-existing form node therefore generates a notice. A check was put in place to ensure the form node exist before checking the node id. Check was also added to ensure `nid` exist before comparing it with 
the value of `variable_get('emergency_contact_webform_nid')`
=> PCHR-4404: Undefined property error on Create HR Documents Page - SSP

civihr_employee_portal/civihr_employee_portal.module
Currently If a logged in user tries to visit the `/welcome-page` or `/welcome-page?destination=welcome-page` URL, an access forbidden page is returned since only the anonymous user is allowed to view this [page](https://github.com/compucorp/civihr-employee-portal/blob/04529d4917c513dbf428e3b5107b85be58082297/civihr_employee_portal/features/civihr_employee_portal_features/civihr_employee_portal_features.pages_default.inc#L676). This PR makes changes such that when a logged in user visits any of the above URL's the user is directed to either the SSP or Admin dashboard based on the user access.
A logged in user sees an access forbidden page when trying to access any of the following URL's: `/welcome-page` or `/welcome-page?destination=welcome-page`
The logged in user is redirected to either …
=> PCHR-4456: Redirect to Appropriate Dashboard If Logged In User Tries To Visit Welcome Page

civihr_employee_portal/updates/7044.php
In SSP, users with two Personal addresses sees one in the view mode of "My Details", and the second while editing. When "My Details" page gets rendered, an API call made to select contact address, limiting to only one record (the first record on the list, irrespective of whether `is_primary` is true). When editing, the Personal address with `is_primary` gets selected. If the second personal address was created with  is_primary TRUE, the first address will have is_primary FALSE. This PR updates the addresses to ensure there is only one personal address by setting the other to work address. There should be only one Personal Address in the system, and that should be the one visible to staff in view and edit modes.
Contact details in SSP shows different address in viewing and editing mode …
=> PCHR-4405: User sees different address when viewing and editing personal details

civihr_employee_portal/src/View/MyDetailsView.php
On SSP dashboard, a notice for `undefined  index: role_revision_id` is displayed 
On SSP dashboard, a notice 'Notice: Undefined index: role_revision_id in Drupal\civihr_employee_portal\View\MyDetailsView->alter() 
(line 30 of /home/compucorp/buildkit/build/test-1/sites/all/modules/civihr-custom/civihr_employee_portal/src/View/MyDetailsView.php).` is displayed.
This notice is not observed for all contacts, only contacts that has the `role_revision_id` column as NULL for the current revision. When the `role_revision_id` is NULL, it is not part of the returned revision result via the Civi [API](https://github.com/compucorp/civihr-employee-portal/blob/f0c8c3bb28fbd63ada576cece444968a6418fc02/civihr_employee_portal/src/View/MyDetailsView.php#L58), hence the reason for the error.
The fix was to …
=> PCHR-4460: Fix 'Undefined index: role_revision_id' Error on SSP Dashboard

civicrm_resources/civicrm_resources.module
When filling the onboarding forms, a warning is usually displayed on the `Home Address` page with 
`Warning: file_get_contents(...)`. This affects three files - require.min.js, reqangular.min.js, and tasks-notification-badge.min.js. The warning can also be noticed on `My Details` page and `Add New Staff Member` page. This warning was fixed in this PR
File get contents warning came up while rendering some pages as part of the resource files could not be loaded.
File get contents warning no longer show on affected pages.
When loading the affected resource files, a leading slash (`/`) was present in the file path. The `/` makes `file_get_contents` start at the top of filesystem, thereby raising a warning. A check was added to [civicrm_resources](https://github.com/compucorp/civihr-employee-po …
=> PCHR-4424: Fixed File Get Contents Warning on Onboarding Form

civihr_employee_portal/civihr_employee_portal.module
When the default download method for files is set to private at `admin/config/media/file-system` and a site logo is uploaded via `admin/appearance/settings`, the logo appears broken and is not visible.
If the download method for files is set to private and a site logo uploaded via `admin/config/media/file-system`, the logo appears broken because the logo file is not a public file.
If the download method for files is set to private and a site logo uploaded via `admin/config/media/file-system`, the logo appears appears normally as is treated as a public file.
To fix this issue, a submit handler function was created for the `theme settings` form at `/admin/appearance/settings`. When the form is saved, the handler checks if the default file scheme is private and if it is, it changes the file …
=> PCHR-4483: Make Logo File Public For Sites With Private File System.
